package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.domain.Audititemlibrary;

import java.util.List;

public interface AudititemlibraryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_audit_item_library
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_audit_item_library
	 * @mbg.generated
	 */
	int insert(Audititemlibrary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_audit_item_library
	 * @mbg.generated
	 */
	Audititemlibrary selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_audit_item_library
	 * @mbg.generated
	 */
	List<Audititemlibrary> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_audit_item_library
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Audititemlibrary record);
}