package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Biditemsupervisor;

import java.util.List;

public interface BiditemsupervisorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bid_item_supervisor
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bid_item_supervisor
	 * @mbg.generated
	 */
	int insert(Biditemsupervisor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bid_item_supervisor
	 * @mbg.generated
	 */
	Biditemsupervisor selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bid_item_supervisor
	 * @mbg.generated
	 */
	List<Biditemsupervisor> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bid_item_supervisor
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Biditemsupervisor record);
}