package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.domain.Column;
import java.util.List;

public interface ColumnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_column
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_column
	 * @mbg.generated
	 */
	int insert(Column record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_column
	 * @mbg.generated
	 */
	Column selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_column
	 * @mbg.generated
	 */
	List<Column> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_column
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Column record);
}