package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Debtbidinvestbill;
import java.util.List;

public interface DebtbidinvestbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_bid_invest_bill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_bid_invest_bill
     *
     * @mbg.generated
     */
    int insert(Debtbidinvestbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_bid_invest_bill
     *
     * @mbg.generated
     */
    Debtbidinvestbill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_bid_invest_bill
     *
     * @mbg.generated
     */
    List<Debtbidinvestbill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_bid_invest_bill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Debtbidinvestbill record);
}