package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Debtitemsupervisor;
import java.util.List;

public interface DebtitemsupervisorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_item_supervisor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_item_supervisor
     *
     * @mbg.generated
     */
    int insert(Debtitemsupervisor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_item_supervisor
     *
     * @mbg.generated
     */
    Debtitemsupervisor selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_item_supervisor
     *
     * @mbg.generated
     */
    List<Debtitemsupervisor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_debt_item_supervisor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Debtitemsupervisor record);
}