package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.domain.Directuser;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface DirectuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_direct_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_direct_user
	 * @mbg.generated
	 */
	int insert(Directuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_direct_user
	 * @mbg.generated
	 */
	Directuser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_direct_user
	 * @mbg.generated
	 */
	List<Directuser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_direct_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Directuser record);

	/**
	 * 通过推荐人id获取被推荐人列表（附带被推荐人信息及其投资情况列表）
	 * @param spreaderId
	 * @return
	 */
	List<Directuser> selectBySpreaderIdWithUserinfoAndInvestList(Long spreaderId);
}