package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Email;

import java.util.List;

public interface EmailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_email
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_email
	 * @mbg.generated
	 */
	int insert(Email record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_email
	 * @mbg.generated
	 */
	Email selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_email
	 * @mbg.generated
	 */
	List<Email> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_email
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Email record);
}