package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Imageplatform;

import java.util.List;

public interface ImageplatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image_platform
     *
     * @mbg.generated
     */
    int insert(Imageplatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image_platform
     *
     * @mbg.generated
     */
    Imageplatform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image_platform
     *
     * @mbg.generated
     */
    List<Imageplatform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_image_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Imageplatform record);
}