package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Invest;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * 投资表mapper
 */
@Component
@Mapper
public interface InvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest
     *
     * @mbg.generated
     */
    int insert(Invest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest
     *
     * @mbg.generated
     */
    Invest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest
     *
     * @mbg.generated
     */
    List<Invest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Invest record);

    /**
     * 根据用户id（user_id）获取用户投资信息
     * @author liuxinwei
     *
     * @param userId the value for t_invest.user_id
     */
     List<Invest> selectByUserId(Long userId);
}