package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Massemailsending;
import java.util.List;

public interface MassemailsendingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email_sending
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email_sending
     *
     * @mbg.generated
     */
    int insert(Massemailsending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email_sending
     *
     * @mbg.generated
     */
    Massemailsending selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email_sending
     *
     * @mbg.generated
     */
    List<Massemailsending> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email_sending
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Massemailsending record);
}