package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Projectproduct;
import java.util.List;

public interface ProjectproductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_product
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_product
	 * @mbg.generated
	 */
	int insert(Projectproduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_product
	 * @mbg.generated
	 */
	Projectproduct selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_product
	 * @mbg.generated
	 */
	List<Projectproduct> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_product
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Projectproduct record);
}