package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Projectrepeat;
import java.util.List;

public interface ProjectrepeatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_repeat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_repeat
     *
     * @mbg.generated
     */
    int insert(Projectrepeat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_repeat
     *
     * @mbg.generated
     */
    Projectrepeat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_repeat
     *
     * @mbg.generated
     */
    List<Projectrepeat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_repeat
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Projectrepeat record);
}