package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.domain.Projectratediff;
import java.util.List;

public interface ProjectratediffMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_rate_diff
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_rate_diff
	 * @mbg.generated
	 */
	int insert(Projectratediff record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_rate_diff
	 * @mbg.generated
	 */
	Projectratediff selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_rate_diff
	 * @mbg.generated
	 */
	List<Projectratediff> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_project_rate_diff
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Projectratediff record);
}