package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Rechargeuser;

import java.util.List;

public interface RechargeuserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_recharge_user
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_recharge_user
	 * @mbg.generated
	 */
	int insert(Rechargeuser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_recharge_user
	 * @mbg.generated
	 */
	Rechargeuser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_recharge_user
	 * @mbg.generated
	 */
	List<Rechargeuser> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_recharge_user
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Rechargeuser record);
}