package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Settingplatform;

import java.util.List;

public interface SettingplatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting_platform
     *
     * @mbg.generated
     */
    int insert(Settingplatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting_platform
     *
     * @mbg.generated
     */
    Settingplatform selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting_platform
     *
     * @mbg.generated
     */
    List<Settingplatform> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_setting_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Settingplatform record);
}