package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.domain.Templatepact;
import java.util.List;

public interface TemplatepactMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_template_pact
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_template_pact
	 * @mbg.generated
	 */
	int insert(Templatepact record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_template_pact
	 * @mbg.generated
	 */
	Templatepact selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_template_pact
	 * @mbg.generated
	 */
	List<Templatepact> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_template_pact
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Templatepact record);
}