package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.domain.Theme;

import java.util.List;

public interface ThemeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_theme
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_theme
	 * @mbg.generated
	 */
	int insert(Theme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_theme
	 * @mbg.generated
	 */
	Theme selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_theme
	 * @mbg.generated
	 */
	List<Theme> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_theme
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Theme record);
}