package com.juqijinfu.p2p.platform.mapper;

import com.juqijinfu.p2p.platform.model.Userfund;

import java.util.List;

public interface UserfundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_fund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_fund
     *
     * @mbg.generated
     */
    int insert(Userfund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_fund
     *
     * @mbg.generated
     */
    Userfund selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_fund
     *
     * @mbg.generated
     */
    List<Userfund> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_fund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Userfund record);
}