package com.juqijinfu.p2p.platform.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_auto_invest_setting
 */
public class Autoinvestsetting {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 添加时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 用户ID This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 状态 0 关闭 1 开启 This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.status
	 * @mbg.generated
	 */
	private Boolean status;
	/**
	 * Database Column Remarks: 每笔次投资金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.amount
	 * @mbg.generated
	 */
	private BigDecimal amount;
	/**
	 * Database Column Remarks: 最低年利率 This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.min_apr
	 * @mbg.generated
	 */
	private BigDecimal minApr;
	/**
	 * Database Column Remarks: 最长投资期限(月) This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.max_period
	 * @mbg.generated
	 */
	private Byte maxPeriod;
	/**
	 * Database Column Remarks: 排队等待时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_auto_invest_setting.wait_time
	 * @mbg.generated
	 */
	private Date waitTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.id
	 * @return  the value of t_auto_invest_setting.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.id
	 * @param id  the value for t_auto_invest_setting.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.time
	 * @return  the value of t_auto_invest_setting.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.time
	 * @param time  the value for t_auto_invest_setting.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.user_id
	 * @return  the value of t_auto_invest_setting.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.user_id
	 * @param userId  the value for t_auto_invest_setting.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.status
	 * @return  the value of t_auto_invest_setting.status
	 * @mbg.generated
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.status
	 * @param status  the value for t_auto_invest_setting.status
	 * @mbg.generated
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.amount
	 * @return  the value of t_auto_invest_setting.amount
	 * @mbg.generated
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.amount
	 * @param amount  the value for t_auto_invest_setting.amount
	 * @mbg.generated
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.min_apr
	 * @return  the value of t_auto_invest_setting.min_apr
	 * @mbg.generated
	 */
	public BigDecimal getMinApr() {
		return minApr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.min_apr
	 * @param minApr  the value for t_auto_invest_setting.min_apr
	 * @mbg.generated
	 */
	public void setMinApr(BigDecimal minApr) {
		this.minApr = minApr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.max_period
	 * @return  the value of t_auto_invest_setting.max_period
	 * @mbg.generated
	 */
	public Byte getMaxPeriod() {
		return maxPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.max_period
	 * @param maxPeriod  the value for t_auto_invest_setting.max_period
	 * @mbg.generated
	 */
	public void setMaxPeriod(Byte maxPeriod) {
		this.maxPeriod = maxPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_auto_invest_setting.wait_time
	 * @return  the value of t_auto_invest_setting.wait_time
	 * @mbg.generated
	 */
	public Date getWaitTime() {
		return waitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_auto_invest_setting.wait_time
	 * @param waitTime  the value for t_auto_invest_setting.wait_time
	 * @mbg.generated
	 */
	public void setWaitTime(Date waitTime) {
		this.waitTime = waitTime;
	}
}