package com.juqijinfu.p2p.platform.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bid_item_supervisor
 */
public class Biditemsupervisor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 上传时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 管理员ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.supervisor_id
	 * @mbg.generated
	 */
	private Long supervisorId;
	/**
	 * Database Column Remarks: 借款标ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.bid_id
	 * @mbg.generated
	 */
	private Long bidId;
	/**
	 * Database Column Remarks: 标的审核科目ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.bid_audit_subject_id
	 * @mbg.generated
	 */
	private Long bidAuditSubjectId;
	/**
	 * Database Column Remarks: 图片名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 图片路径 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid_item_supervisor.url
	 * @mbg.generated
	 */
	private String url;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.id
	 * @return  the value of t_bid_item_supervisor.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.id
	 * @param id  the value for t_bid_item_supervisor.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.time
	 * @return  the value of t_bid_item_supervisor.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.time
	 * @param time  the value for t_bid_item_supervisor.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.supervisor_id
	 * @return  the value of t_bid_item_supervisor.supervisor_id
	 * @mbg.generated
	 */
	public Long getSupervisorId() {
		return supervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.supervisor_id
	 * @param supervisorId  the value for t_bid_item_supervisor.supervisor_id
	 * @mbg.generated
	 */
	public void setSupervisorId(Long supervisorId) {
		this.supervisorId = supervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.bid_id
	 * @return  the value of t_bid_item_supervisor.bid_id
	 * @mbg.generated
	 */
	public Long getBidId() {
		return bidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.bid_id
	 * @param bidId  the value for t_bid_item_supervisor.bid_id
	 * @mbg.generated
	 */
	public void setBidId(Long bidId) {
		this.bidId = bidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.bid_audit_subject_id
	 * @return  the value of t_bid_item_supervisor.bid_audit_subject_id
	 * @mbg.generated
	 */
	public Long getBidAuditSubjectId() {
		return bidAuditSubjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.bid_audit_subject_id
	 * @param bidAuditSubjectId  the value for t_bid_item_supervisor.bid_audit_subject_id
	 * @mbg.generated
	 */
	public void setBidAuditSubjectId(Long bidAuditSubjectId) {
		this.bidAuditSubjectId = bidAuditSubjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.name
	 * @return  the value of t_bid_item_supervisor.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.name
	 * @param name  the value for t_bid_item_supervisor.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid_item_supervisor.url
	 * @return  the value of t_bid_item_supervisor.url
	 * @mbg.generated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid_item_supervisor.url
	 * @param url  the value for t_bid_item_supervisor.url
	 * @mbg.generated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}
}