package com.juqijinfu.p2p.platform.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bill_invest
 */
public class Billinvest {

	/**
	 * Database Column Remarks: 账单id This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 生成时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 投资人ID(冗余) This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 投资ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.invest_id
	 * @mbg.generated
	 */
	private Long investId;
	/**
	 * Database Column Remarks: 借款标ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.bid_id
	 * @mbg.generated
	 */
	private Long bidId;
	/**
	 * Database Column Remarks: 期数 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.period
	 * @mbg.generated
	 */
	private Integer period;
	/**
	 * Database Column Remarks: 借款标标题(冗余) This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * Database Column Remarks: 收款时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.receive_time
	 * @mbg.generated
	 */
	private Date receiveTime;
	/**
	 * Database Column Remarks: 本期应收款金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.receive_corpus
	 * @mbg.generated
	 */
	private BigDecimal receiveCorpus;
	/**
	 * Database Column Remarks: 本期应收利息 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.receive_interest
	 * @mbg.generated
	 */
	private BigDecimal receiveInterest;
	/**
	 * Database Column Remarks: 是否逾期。0-未逾期；1-逾期 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.is_overdue
	 * @mbg.generated
	 */
	private Boolean isOverdue;
	/**
	 * Database Column Remarks: 逾期罚息 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.overdue_fine
	 * @mbg.generated
	 */
	private BigDecimal overdueFine;
	/**
	 * Database Column Remarks: 逾期天数 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.overdue_days
	 * @mbg.generated
	 */
	private Integer overdueDays;
	/**
	 * Database Column Remarks: 收款状态: 0-待还； 1-已还； 2-已转让; This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 实际收款时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.real_receive_time
	 * @mbg.generated
	 */
	private Date realReceiveTime;
	/**
	 * Database Column Remarks: 加息金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.add_invest
	 * @mbg.generated
	 */
	private BigDecimal addInvest;
	/**
	 * Database Column Remarks: 加息券状态：0.未发放、1.已发放 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.rate_status
	 * @mbg.generated
	 */
	private Byte rateStatus;
	/**
	 * Database Column Remarks: 实际发放加息券金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.real_add_invest
	 * @mbg.generated
	 */
	private BigDecimal realAddInvest;
	/**
	 * Database Column Remarks: 加息金额发放服务号 This field was generated by MyBatis Generator. This field corresponds to the database column t_bill_invest.rate_service_no
	 * @mbg.generated
	 */
	private String rateServiceNo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.id
	 * @return  the value of t_bill_invest.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.id
	 * @param id  the value for t_bill_invest.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.time
	 * @return  the value of t_bill_invest.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.time
	 * @param time  the value for t_bill_invest.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.user_id
	 * @return  the value of t_bill_invest.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.user_id
	 * @param userId  the value for t_bill_invest.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.invest_id
	 * @return  the value of t_bill_invest.invest_id
	 * @mbg.generated
	 */
	public Long getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.invest_id
	 * @param investId  the value for t_bill_invest.invest_id
	 * @mbg.generated
	 */
	public void setInvestId(Long investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.bid_id
	 * @return  the value of t_bill_invest.bid_id
	 * @mbg.generated
	 */
	public Long getBidId() {
		return bidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.bid_id
	 * @param bidId  the value for t_bill_invest.bid_id
	 * @mbg.generated
	 */
	public void setBidId(Long bidId) {
		this.bidId = bidId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.period
	 * @return  the value of t_bill_invest.period
	 * @mbg.generated
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.period
	 * @param period  the value for t_bill_invest.period
	 * @mbg.generated
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.title
	 * @return  the value of t_bill_invest.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.title
	 * @param title  the value for t_bill_invest.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.receive_time
	 * @return  the value of t_bill_invest.receive_time
	 * @mbg.generated
	 */
	public Date getReceiveTime() {
		return receiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.receive_time
	 * @param receiveTime  the value for t_bill_invest.receive_time
	 * @mbg.generated
	 */
	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.receive_corpus
	 * @return  the value of t_bill_invest.receive_corpus
	 * @mbg.generated
	 */
	public BigDecimal getReceiveCorpus() {
		return receiveCorpus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.receive_corpus
	 * @param receiveCorpus  the value for t_bill_invest.receive_corpus
	 * @mbg.generated
	 */
	public void setReceiveCorpus(BigDecimal receiveCorpus) {
		this.receiveCorpus = receiveCorpus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.receive_interest
	 * @return  the value of t_bill_invest.receive_interest
	 * @mbg.generated
	 */
	public BigDecimal getReceiveInterest() {
		return receiveInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.receive_interest
	 * @param receiveInterest  the value for t_bill_invest.receive_interest
	 * @mbg.generated
	 */
	public void setReceiveInterest(BigDecimal receiveInterest) {
		this.receiveInterest = receiveInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.is_overdue
	 * @return  the value of t_bill_invest.is_overdue
	 * @mbg.generated
	 */
	public Boolean getIsOverdue() {
		return isOverdue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.is_overdue
	 * @param isOverdue  the value for t_bill_invest.is_overdue
	 * @mbg.generated
	 */
	public void setIsOverdue(Boolean isOverdue) {
		this.isOverdue = isOverdue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.overdue_fine
	 * @return  the value of t_bill_invest.overdue_fine
	 * @mbg.generated
	 */
	public BigDecimal getOverdueFine() {
		return overdueFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.overdue_fine
	 * @param overdueFine  the value for t_bill_invest.overdue_fine
	 * @mbg.generated
	 */
	public void setOverdueFine(BigDecimal overdueFine) {
		this.overdueFine = overdueFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.overdue_days
	 * @return  the value of t_bill_invest.overdue_days
	 * @mbg.generated
	 */
	public Integer getOverdueDays() {
		return overdueDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.overdue_days
	 * @param overdueDays  the value for t_bill_invest.overdue_days
	 * @mbg.generated
	 */
	public void setOverdueDays(Integer overdueDays) {
		this.overdueDays = overdueDays;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.status
	 * @return  the value of t_bill_invest.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.status
	 * @param status  the value for t_bill_invest.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.real_receive_time
	 * @return  the value of t_bill_invest.real_receive_time
	 * @mbg.generated
	 */
	public Date getRealReceiveTime() {
		return realReceiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.real_receive_time
	 * @param realReceiveTime  the value for t_bill_invest.real_receive_time
	 * @mbg.generated
	 */
	public void setRealReceiveTime(Date realReceiveTime) {
		this.realReceiveTime = realReceiveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.add_invest
	 * @return  the value of t_bill_invest.add_invest
	 * @mbg.generated
	 */
	public BigDecimal getAddInvest() {
		return addInvest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.add_invest
	 * @param addInvest  the value for t_bill_invest.add_invest
	 * @mbg.generated
	 */
	public void setAddInvest(BigDecimal addInvest) {
		this.addInvest = addInvest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.rate_status
	 * @return  the value of t_bill_invest.rate_status
	 * @mbg.generated
	 */
	public Byte getRateStatus() {
		return rateStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.rate_status
	 * @param rateStatus  the value for t_bill_invest.rate_status
	 * @mbg.generated
	 */
	public void setRateStatus(Byte rateStatus) {
		this.rateStatus = rateStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.real_add_invest
	 * @return  the value of t_bill_invest.real_add_invest
	 * @mbg.generated
	 */
	public BigDecimal getRealAddInvest() {
		return realAddInvest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.real_add_invest
	 * @param realAddInvest  the value for t_bill_invest.real_add_invest
	 * @mbg.generated
	 */
	public void setRealAddInvest(BigDecimal realAddInvest) {
		this.realAddInvest = realAddInvest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bill_invest.rate_service_no
	 * @return  the value of t_bill_invest.rate_service_no
	 * @mbg.generated
	 */
	public String getRateServiceNo() {
		return rateServiceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bill_invest.rate_service_no
	 * @param rateServiceNo  the value for t_bill_invest.rate_service_no
	 * @mbg.generated
	 */
	public void setRateServiceNo(String rateServiceNo) {
		this.rateServiceNo = rateServiceNo == null ? null : rateServiceNo.trim();
	}
}