package com.juqijinfu.p2p.platform.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_direct_user
 */
public class Directuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 用户id(被推广人) This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 推广人id This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.spreader_id
	 * @mbg.generated
	 */
	private Long spreaderId;
	/**
	 * Database Column Remarks: 被推广人累计理财 This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.total_invest
	 * @mbg.generated
	 */
	private BigDecimal totalInvest;
	/**
	 * Database Column Remarks: 一级推广累计返佣 This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.first_total_rebate
	 * @mbg.generated
	 */
	private BigDecimal firstTotalRebate;
	/**
	 * Database Column Remarks: 二级推广累计返佣 This field was generated by MyBatis Generator. This field corresponds to the database column t_direct_user.second_total_rebate
	 * @mbg.generated
	 */
	private BigDecimal secondTotalRebate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.id
	 * @return  the value of t_direct_user.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.id
	 * @param id  the value for t_direct_user.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.time
	 * @return  the value of t_direct_user.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.time
	 * @param time  the value for t_direct_user.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.user_id
	 * @return  the value of t_direct_user.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.user_id
	 * @param userId  the value for t_direct_user.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.spreader_id
	 * @return  the value of t_direct_user.spreader_id
	 * @mbg.generated
	 */
	public Long getSpreaderId() {
		return spreaderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.spreader_id
	 * @param spreaderId  the value for t_direct_user.spreader_id
	 * @mbg.generated
	 */
	public void setSpreaderId(Long spreaderId) {
		this.spreaderId = spreaderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.total_invest
	 * @return  the value of t_direct_user.total_invest
	 * @mbg.generated
	 */
	public BigDecimal getTotalInvest() {
		return totalInvest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.total_invest
	 * @param totalInvest  the value for t_direct_user.total_invest
	 * @mbg.generated
	 */
	public void setTotalInvest(BigDecimal totalInvest) {
		this.totalInvest = totalInvest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.first_total_rebate
	 * @return  the value of t_direct_user.first_total_rebate
	 * @mbg.generated
	 */
	public BigDecimal getFirstTotalRebate() {
		return firstTotalRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.first_total_rebate
	 * @param firstTotalRebate  the value for t_direct_user.first_total_rebate
	 * @mbg.generated
	 */
	public void setFirstTotalRebate(BigDecimal firstTotalRebate) {
		this.firstTotalRebate = firstTotalRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_direct_user.second_total_rebate
	 * @return  the value of t_direct_user.second_total_rebate
	 * @mbg.generated
	 */
	public BigDecimal getSecondTotalRebate() {
		return secondTotalRebate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_direct_user.second_total_rebate
	 * @param secondTotalRebate  the value for t_direct_user.second_total_rebate
	 * @mbg.generated
	 */
	public void setSecondTotalRebate(BigDecimal secondTotalRebate) {
		this.secondTotalRebate = secondTotalRebate;
	}
}