package com.juqijinfu.p2p.platform.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_event_supervisor
 */
public class Eventsupervisor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_event_supervisor.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 操作时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_event_supervisor.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 管理员ID This field was generated by MyBatis Generator. This field corresponds to the database column t_event_supervisor.supervisor_id
	 * @mbg.generated
	 */
	private Long supervisorId;
	/**
	 * Database Column Remarks: IP This field was generated by MyBatis Generator. This field corresponds to the database column t_event_supervisor.ip
	 * @mbg.generated
	 */
	private String ip;
	/**
	 * Database Column Remarks: 操作类型 This field was generated by MyBatis Generator. This field corresponds to the database column t_event_supervisor.item
	 * @mbg.generated
	 */
	private Integer item;
	/**
	 * Database Column Remarks: 描述 This field was generated by MyBatis Generator. This field corresponds to the database column t_event_supervisor.description
	 * @mbg.generated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_event_supervisor.id
	 * @return  the value of t_event_supervisor.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_event_supervisor.id
	 * @param id  the value for t_event_supervisor.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_event_supervisor.time
	 * @return  the value of t_event_supervisor.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_event_supervisor.time
	 * @param time  the value for t_event_supervisor.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_event_supervisor.supervisor_id
	 * @return  the value of t_event_supervisor.supervisor_id
	 * @mbg.generated
	 */
	public Long getSupervisorId() {
		return supervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_event_supervisor.supervisor_id
	 * @param supervisorId  the value for t_event_supervisor.supervisor_id
	 * @mbg.generated
	 */
	public void setSupervisorId(Long supervisorId) {
		this.supervisorId = supervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_event_supervisor.ip
	 * @return  the value of t_event_supervisor.ip
	 * @mbg.generated
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_event_supervisor.ip
	 * @param ip  the value for t_event_supervisor.ip
	 * @mbg.generated
	 */
	public void setIp(String ip) {
		this.ip = ip == null ? null : ip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_event_supervisor.item
	 * @return  the value of t_event_supervisor.item
	 * @mbg.generated
	 */
	public Integer getItem() {
		return item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_event_supervisor.item
	 * @param item  the value for t_event_supervisor.item
	 * @mbg.generated
	 */
	public void setItem(Integer item) {
		this.item = item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_event_supervisor.description
	 * @return  the value of t_event_supervisor.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_event_supervisor.description
	 * @param description  the value for t_event_supervisor.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}