package com.juqijinfu.p2p.platform.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mass_email_sending
 */
public class Massemailsending {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 添加时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 收件人邮箱 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * Database Column Remarks: 邮件主题 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * Database Column Remarks: 是否已经发送 0-否 1-是 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.is_send
	 * @mbg.generated
	 */
	private Boolean isSend;
	/**
	 * Database Column Remarks: 尝试次数 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.try_times
	 * @mbg.generated
	 */
	private Byte tryTimes;
	/**
	 * Database Column Remarks: 发送时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.send_time
	 * @mbg.generated
	 */
	private Date sendTime;
	/**
	 * Database Column Remarks: 邮件内容 This field was generated by MyBatis Generator. This field corresponds to the database column t_mass_email_sending.content
	 * @mbg.generated
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.id
	 * @return  the value of t_mass_email_sending.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.id
	 * @param id  the value for t_mass_email_sending.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.time
	 * @return  the value of t_mass_email_sending.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.time
	 * @param time  the value for t_mass_email_sending.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.email
	 * @return  the value of t_mass_email_sending.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.email
	 * @param email  the value for t_mass_email_sending.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.title
	 * @return  the value of t_mass_email_sending.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.title
	 * @param title  the value for t_mass_email_sending.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.is_send
	 * @return  the value of t_mass_email_sending.is_send
	 * @mbg.generated
	 */
	public Boolean getIsSend() {
		return isSend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.is_send
	 * @param isSend  the value for t_mass_email_sending.is_send
	 * @mbg.generated
	 */
	public void setIsSend(Boolean isSend) {
		this.isSend = isSend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.try_times
	 * @return  the value of t_mass_email_sending.try_times
	 * @mbg.generated
	 */
	public Byte getTryTimes() {
		return tryTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.try_times
	 * @param tryTimes  the value for t_mass_email_sending.try_times
	 * @mbg.generated
	 */
	public void setTryTimes(Byte tryTimes) {
		this.tryTimes = tryTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.send_time
	 * @return  the value of t_mass_email_sending.send_time
	 * @mbg.generated
	 */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.send_time
	 * @param sendTime  the value for t_mass_email_sending.send_time
	 * @mbg.generated
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mass_email_sending.content
	 * @return  the value of t_mass_email_sending.content
	 * @mbg.generated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mass_email_sending.content
	 * @param content  the value for t_mass_email_sending.content
	 * @mbg.generated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}
}