package com.juqijinfu.p2p.platform.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_payment_request
 */
public class Paymentrequest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 关联用户ID This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 托管业务订单号(每次托管操作生成，全局唯一) This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.service_order_no
	 * @mbg.generated
	 */
	private String serviceOrderNo;
	/**
	 * Database Column Remarks: 托管业务类型 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.service_type
	 * @mbg.generated
	 */
	private Integer serviceType;
	/**
	 * Database Column Remarks: 交易订单号 说明： 用于第三方接口对接； 有重复交易可能时，多次请求订单号固定 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.order_no
	 * @mbg.generated
	 */
	private String orderNo;
	/**
	 * Database Column Remarks: 第三方托管接口交易类型 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.pay_type
	 * @mbg.generated
	 */
	private Integer payType;
	/**
	 * Database Column Remarks: 状态： -1-失败； 0-处理中； 1-成功 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 交易完成时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.completed_time
	 * @mbg.generated
	 */
	private Date completedTime;
	/**
	 * Database Column Remarks: 日志补单地址，异步回调地址 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.ayns_url
	 * @mbg.generated
	 */
	private String aynsUrl;
	/**
	 * Database Column Remarks: 托管请求唯一标识UUID This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.mark
	 * @mbg.generated
	 */
	private String mark;
	/**
	 * Database Column Remarks: 接口请求提交参数 This field was generated by MyBatis Generator. This field corresponds to the database column t_payment_request.req_params
	 * @mbg.generated
	 */
	private String reqParams;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.id
	 * @return  the value of t_payment_request.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.id
	 * @param id  the value for t_payment_request.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.time
	 * @return  the value of t_payment_request.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.time
	 * @param time  the value for t_payment_request.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.user_id
	 * @return  the value of t_payment_request.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.user_id
	 * @param userId  the value for t_payment_request.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.service_order_no
	 * @return  the value of t_payment_request.service_order_no
	 * @mbg.generated
	 */
	public String getServiceOrderNo() {
		return serviceOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.service_order_no
	 * @param serviceOrderNo  the value for t_payment_request.service_order_no
	 * @mbg.generated
	 */
	public void setServiceOrderNo(String serviceOrderNo) {
		this.serviceOrderNo = serviceOrderNo == null ? null : serviceOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.service_type
	 * @return  the value of t_payment_request.service_type
	 * @mbg.generated
	 */
	public Integer getServiceType() {
		return serviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.service_type
	 * @param serviceType  the value for t_payment_request.service_type
	 * @mbg.generated
	 */
	public void setServiceType(Integer serviceType) {
		this.serviceType = serviceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.order_no
	 * @return  the value of t_payment_request.order_no
	 * @mbg.generated
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.order_no
	 * @param orderNo  the value for t_payment_request.order_no
	 * @mbg.generated
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo == null ? null : orderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.pay_type
	 * @return  the value of t_payment_request.pay_type
	 * @mbg.generated
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.pay_type
	 * @param payType  the value for t_payment_request.pay_type
	 * @mbg.generated
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.status
	 * @return  the value of t_payment_request.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.status
	 * @param status  the value for t_payment_request.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.completed_time
	 * @return  the value of t_payment_request.completed_time
	 * @mbg.generated
	 */
	public Date getCompletedTime() {
		return completedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.completed_time
	 * @param completedTime  the value for t_payment_request.completed_time
	 * @mbg.generated
	 */
	public void setCompletedTime(Date completedTime) {
		this.completedTime = completedTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.ayns_url
	 * @return  the value of t_payment_request.ayns_url
	 * @mbg.generated
	 */
	public String getAynsUrl() {
		return aynsUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.ayns_url
	 * @param aynsUrl  the value for t_payment_request.ayns_url
	 * @mbg.generated
	 */
	public void setAynsUrl(String aynsUrl) {
		this.aynsUrl = aynsUrl == null ? null : aynsUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.mark
	 * @return  the value of t_payment_request.mark
	 * @mbg.generated
	 */
	public String getMark() {
		return mark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.mark
	 * @param mark  the value for t_payment_request.mark
	 * @mbg.generated
	 */
	public void setMark(String mark) {
		this.mark = mark == null ? null : mark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_payment_request.req_params
	 * @return  the value of t_payment_request.req_params
	 * @mbg.generated
	 */
	public String getReqParams() {
		return reqParams;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_payment_request.req_params
	 * @param reqParams  the value for t_payment_request.req_params
	 * @mbg.generated
	 */
	public void setReqParams(String reqParams) {
		this.reqParams = reqParams == null ? null : reqParams.trim();
	}
}