package com.juqijinfu.p2p.platform.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_red_packet_user
 */
public class Redpacketuser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 红包唯一标识 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user._key
	 * @mbg.generated
	 */
	private String key;
	/**
	 * Database Column Remarks: 红包名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.red_packet_name
	 * @mbg.generated
	 */
	private String redPacketName;
	/**
	 * Database Column Remarks: 关联用户ID This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 红包金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.amount
	 * @mbg.generated
	 */
	private BigDecimal amount;
	/**
	 * Database Column Remarks: 锁定时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.lock_time
	 * @mbg.generated
	 */
	private Date lockTime;
	/**
	 * Database Column Remarks: 投标ID This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.invest_id
	 * @mbg.generated
	 */
	private Long investId;
	/**
	 * Database Column Remarks: 红包使用规则(投资大于等于这个金额） This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.use_rule
	 * @mbg.generated
	 */
	private BigDecimal useRule;
	/**
	 * Database Column Remarks: 红包的有效期单位天 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.limit_day
	 * @mbg.generated
	 */
	private Integer limitDay;
	/**
	 * Database Column Remarks: 红包有效时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.limit_time
	 * @mbg.generated
	 */
	private Date limitTime;
	/**
	 * Database Column Remarks: 使用状况 0(未激活) , 1(未领取) ,2（已领取）, 3（已使用）,-1（已过期）,-2(使用中) This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 唯一键 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_user.seq
	 * @mbg.generated
	 */
	private String seq;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.id
	 * @return  the value of t_red_packet_user.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.id
	 * @param id  the value for t_red_packet_user.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.time
	 * @return  the value of t_red_packet_user.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.time
	 * @param time  the value for t_red_packet_user.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user._key
	 * @return  the value of t_red_packet_user._key
	 * @mbg.generated
	 */
	public String getKey() {
		return key;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user._key
	 * @param key  the value for t_red_packet_user._key
	 * @mbg.generated
	 */
	public void setKey(String key) {
		this.key = key == null ? null : key.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.red_packet_name
	 * @return  the value of t_red_packet_user.red_packet_name
	 * @mbg.generated
	 */
	public String getRedPacketName() {
		return redPacketName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.red_packet_name
	 * @param redPacketName  the value for t_red_packet_user.red_packet_name
	 * @mbg.generated
	 */
	public void setRedPacketName(String redPacketName) {
		this.redPacketName = redPacketName == null ? null : redPacketName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.user_id
	 * @return  the value of t_red_packet_user.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.user_id
	 * @param userId  the value for t_red_packet_user.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.amount
	 * @return  the value of t_red_packet_user.amount
	 * @mbg.generated
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.amount
	 * @param amount  the value for t_red_packet_user.amount
	 * @mbg.generated
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.lock_time
	 * @return  the value of t_red_packet_user.lock_time
	 * @mbg.generated
	 */
	public Date getLockTime() {
		return lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.lock_time
	 * @param lockTime  the value for t_red_packet_user.lock_time
	 * @mbg.generated
	 */
	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.invest_id
	 * @return  the value of t_red_packet_user.invest_id
	 * @mbg.generated
	 */
	public Long getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.invest_id
	 * @param investId  the value for t_red_packet_user.invest_id
	 * @mbg.generated
	 */
	public void setInvestId(Long investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.use_rule
	 * @return  the value of t_red_packet_user.use_rule
	 * @mbg.generated
	 */
	public BigDecimal getUseRule() {
		return useRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.use_rule
	 * @param useRule  the value for t_red_packet_user.use_rule
	 * @mbg.generated
	 */
	public void setUseRule(BigDecimal useRule) {
		this.useRule = useRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.limit_day
	 * @return  the value of t_red_packet_user.limit_day
	 * @mbg.generated
	 */
	public Integer getLimitDay() {
		return limitDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.limit_day
	 * @param limitDay  the value for t_red_packet_user.limit_day
	 * @mbg.generated
	 */
	public void setLimitDay(Integer limitDay) {
		this.limitDay = limitDay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.limit_time
	 * @return  the value of t_red_packet_user.limit_time
	 * @mbg.generated
	 */
	public Date getLimitTime() {
		return limitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.limit_time
	 * @param limitTime  the value for t_red_packet_user.limit_time
	 * @mbg.generated
	 */
	public void setLimitTime(Date limitTime) {
		this.limitTime = limitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.status
	 * @return  the value of t_red_packet_user.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.status
	 * @param status  the value for t_red_packet_user.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_user.seq
	 * @return  the value of t_red_packet_user.seq
	 * @mbg.generated
	 */
	public String getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_user.seq
	 * @param seq  the value for t_red_packet_user.seq
	 * @mbg.generated
	 */
	public void setSeq(String seq) {
		this.seq = seq == null ? null : seq.trim();
	}
}