package com.juqijinfu.p2p.platform.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_right_action
 */
public class Rightaction {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_right_action.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 权限id This field was generated by MyBatis Generator. This field corresponds to the database column t_right_action.right_id
	 * @mbg.generated
	 */
	private Long rightId;
	/**
	 * Database Column Remarks: 路由对应的action This field was generated by MyBatis Generator. This field corresponds to the database column t_right_action.action
	 * @mbg.generated
	 */
	private String action;
	/**
	 * Database Column Remarks: 描述 This field was generated by MyBatis Generator. This field corresponds to the database column t_right_action.description
	 * @mbg.generated
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right_action.id
	 * @return  the value of t_right_action.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right_action.id
	 * @param id  the value for t_right_action.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right_action.right_id
	 * @return  the value of t_right_action.right_id
	 * @mbg.generated
	 */
	public Long getRightId() {
		return rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right_action.right_id
	 * @param rightId  the value for t_right_action.right_id
	 * @mbg.generated
	 */
	public void setRightId(Long rightId) {
		this.rightId = rightId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right_action.action
	 * @return  the value of t_right_action.action
	 * @mbg.generated
	 */
	public String getAction() {
		return action;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right_action.action
	 * @param action  the value for t_right_action.action
	 * @mbg.generated
	 */
	public void setAction(String action) {
		this.action = action == null ? null : action.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_right_action.description
	 * @return  the value of t_right_action.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_right_action.description
	 * @param description  the value for t_right_action.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}
}