package com.juqijinfu.p2p.platform.domain;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_info
 */
public class Userinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 用户ID(取t_users表的ID) This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 用户昵称(冗余自t_users表) This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 注册入口: 1-pc  2-android  3-ios  4-wechat  This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.client
	 * @mbg.generated
	 */
	private Byte client;
	/**
	 * Database Column Remarks: 用户头像路径 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.photo
	 * @mbg.generated
	 */
	private String photo;
	/**
	 * Database Column Remarks: 真实姓名 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.reality_name
	 * @mbg.generated
	 */
	private String realityName;
	/**
	 * Database Column Remarks: 身份证号码 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.id_number
	 * @mbg.generated
	 */
	private String idNumber;
	/**
	 * Database Column Remarks: 手机号码 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.mobile
	 * @mbg.generated
	 */
	private String mobile;
	/**
	 * Database Column Remarks: 邮箱 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.email
	 * @mbg.generated
	 */
	private String email;
	/**
	 * Database Column Remarks: 箱邮是否已经验证通过 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.is_email_verified
	 * @mbg.generated
	 */
	private Boolean isEmailVerified;
	/**
	 * Database Column Remarks: 信用积分 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.credit_score
	 * @mbg.generated
	 */
	private Integer creditScore;
	/**
	 * Database Column Remarks: 信用等级 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.credit_level_id
	 * @mbg.generated
	 */
	private Integer creditLevelId;
	/**
	 * Database Column Remarks: 信用额度 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.credit_line
	 * @mbg.generated
	 */
	private BigDecimal creditLine;
	/**
	 * Database Column Remarks: 1 男 2 女 3 未知 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.sex
	 * @mbg.generated
	 */
	private Byte sex;
	/**
	 * Database Column Remarks: 生日 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.birthday
	 * @mbg.generated
	 */
	private Date birthday;
	/**
	 * Database Column Remarks: 教育情况 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.education
	 * @mbg.generated
	 */
	private Byte education;
	/**
	 * Database Column Remarks: 婚姻状况 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.marital
	 * @mbg.generated
	 */
	private Byte marital;
	/**
	 * Database Column Remarks: 年收入 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.annual_income
	 * @mbg.generated
	 */
	private Byte annualIncome;
	/**
	 * Database Column Remarks: 净资产 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.net_asset
	 * @mbg.generated
	 */
	private Byte netAsset;
	/**
	 * Database Column Remarks: 工作经验 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.work_experience
	 * @mbg.generated
	 */
	private Byte workExperience;
	/**
	 * Database Column Remarks: 房贷情况 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.house
	 * @mbg.generated
	 */
	private Byte house;
	/**
	 * Database Column Remarks: 车贷情况 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.car
	 * @mbg.generated
	 */
	private Byte car;
	/**
	 * Database Column Remarks: 紧急联系人类型：0、未选择；1、父母；2、配偶；3、子女；4、亲戚；5、朋友；6、同事； This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.emergency_contact_type
	 * @mbg.generated
	 */
	private Byte emergencyContactType;
	/**
	 * Database Column Remarks: 紧急联系人姓名 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.emergency_contact_name
	 * @mbg.generated
	 */
	private String emergencyContactName;
	/**
	 * Database Column Remarks: 紧急联系人手机号码 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.emergency_contact_mobile
	 * @mbg.generated
	 */
	private String emergencyContactMobile;
	/**
	 * Database Column Remarks: 会员类型。0-新会员；1-理财会员；2-借款会员；3-复合会员（理财&借款） This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.member_type
	 * @mbg.generated
	 */
	private Boolean memberType;
	/**
	 * Database Column Remarks: 成为借款会员的时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.loan_member_time
	 * @mbg.generated
	 */
	private Date loanMemberTime;
	/**
	 * Database Column Remarks: 成为理财会员的时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.invest_member_time
	 * @mbg.generated
	 */
	private Date investMemberTime;
	/**
	 * Database Column Remarks: 基本信息添加进度 注：每添加一类加1，等于3为完成基本信息添加 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.add_base_info_schedule
	 * @mbg.generated
	 */
	private Byte addBaseInfoSchedule;
	/**
	 * Database Column Remarks: 营业执照编号 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.business_code
	 * @mbg.generated
	 */
	private String businessCode;
	/**
	 * Database Column Remarks: 企业名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_user_info.enterprise_name
	 * @mbg.generated
	 */
	private String enterpriseName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.id
	 * @return  the value of t_user_info.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.id
	 * @param id  the value for t_user_info.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.user_id
	 * @return  the value of t_user_info.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.user_id
	 * @param userId  the value for t_user_info.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.name
	 * @return  the value of t_user_info.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.name
	 * @param name  the value for t_user_info.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.client
	 * @return  the value of t_user_info.client
	 * @mbg.generated
	 */
	public Byte getClient() {
		return client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.client
	 * @param client  the value for t_user_info.client
	 * @mbg.generated
	 */
	public void setClient(Byte client) {
		this.client = client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.photo
	 * @return  the value of t_user_info.photo
	 * @mbg.generated
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.photo
	 * @param photo  the value for t_user_info.photo
	 * @mbg.generated
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.reality_name
	 * @return  the value of t_user_info.reality_name
	 * @mbg.generated
	 */
	public String getRealityName() {
		return realityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.reality_name
	 * @param realityName  the value for t_user_info.reality_name
	 * @mbg.generated
	 */
	public void setRealityName(String realityName) {
		this.realityName = realityName == null ? null : realityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.id_number
	 * @return  the value of t_user_info.id_number
	 * @mbg.generated
	 */
	public String getIdNumber() {
		return idNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.id_number
	 * @param idNumber  the value for t_user_info.id_number
	 * @mbg.generated
	 */
	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber == null ? null : idNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.mobile
	 * @return  the value of t_user_info.mobile
	 * @mbg.generated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.mobile
	 * @param mobile  the value for t_user_info.mobile
	 * @mbg.generated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.email
	 * @return  the value of t_user_info.email
	 * @mbg.generated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.email
	 * @param email  the value for t_user_info.email
	 * @mbg.generated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.is_email_verified
	 * @return  the value of t_user_info.is_email_verified
	 * @mbg.generated
	 */
	public Boolean getIsEmailVerified() {
		return isEmailVerified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.is_email_verified
	 * @param isEmailVerified  the value for t_user_info.is_email_verified
	 * @mbg.generated
	 */
	public void setIsEmailVerified(Boolean isEmailVerified) {
		this.isEmailVerified = isEmailVerified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.credit_score
	 * @return  the value of t_user_info.credit_score
	 * @mbg.generated
	 */
	public Integer getCreditScore() {
		return creditScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.credit_score
	 * @param creditScore  the value for t_user_info.credit_score
	 * @mbg.generated
	 */
	public void setCreditScore(Integer creditScore) {
		this.creditScore = creditScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.credit_level_id
	 * @return  the value of t_user_info.credit_level_id
	 * @mbg.generated
	 */
	public Integer getCreditLevelId() {
		return creditLevelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.credit_level_id
	 * @param creditLevelId  the value for t_user_info.credit_level_id
	 * @mbg.generated
	 */
	public void setCreditLevelId(Integer creditLevelId) {
		this.creditLevelId = creditLevelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.credit_line
	 * @return  the value of t_user_info.credit_line
	 * @mbg.generated
	 */
	public BigDecimal getCreditLine() {
		return creditLine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.credit_line
	 * @param creditLine  the value for t_user_info.credit_line
	 * @mbg.generated
	 */
	public void setCreditLine(BigDecimal creditLine) {
		this.creditLine = creditLine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.sex
	 * @return  the value of t_user_info.sex
	 * @mbg.generated
	 */
	public Byte getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.sex
	 * @param sex  the value for t_user_info.sex
	 * @mbg.generated
	 */
	public void setSex(Byte sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.birthday
	 * @return  the value of t_user_info.birthday
	 * @mbg.generated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.birthday
	 * @param birthday  the value for t_user_info.birthday
	 * @mbg.generated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.education
	 * @return  the value of t_user_info.education
	 * @mbg.generated
	 */
	public Byte getEducation() {
		return education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.education
	 * @param education  the value for t_user_info.education
	 * @mbg.generated
	 */
	public void setEducation(Byte education) {
		this.education = education;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.marital
	 * @return  the value of t_user_info.marital
	 * @mbg.generated
	 */
	public Byte getMarital() {
		return marital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.marital
	 * @param marital  the value for t_user_info.marital
	 * @mbg.generated
	 */
	public void setMarital(Byte marital) {
		this.marital = marital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.annual_income
	 * @return  the value of t_user_info.annual_income
	 * @mbg.generated
	 */
	public Byte getAnnualIncome() {
		return annualIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.annual_income
	 * @param annualIncome  the value for t_user_info.annual_income
	 * @mbg.generated
	 */
	public void setAnnualIncome(Byte annualIncome) {
		this.annualIncome = annualIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.net_asset
	 * @return  the value of t_user_info.net_asset
	 * @mbg.generated
	 */
	public Byte getNetAsset() {
		return netAsset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.net_asset
	 * @param netAsset  the value for t_user_info.net_asset
	 * @mbg.generated
	 */
	public void setNetAsset(Byte netAsset) {
		this.netAsset = netAsset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.work_experience
	 * @return  the value of t_user_info.work_experience
	 * @mbg.generated
	 */
	public Byte getWorkExperience() {
		return workExperience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.work_experience
	 * @param workExperience  the value for t_user_info.work_experience
	 * @mbg.generated
	 */
	public void setWorkExperience(Byte workExperience) {
		this.workExperience = workExperience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.house
	 * @return  the value of t_user_info.house
	 * @mbg.generated
	 */
	public Byte getHouse() {
		return house;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.house
	 * @param house  the value for t_user_info.house
	 * @mbg.generated
	 */
	public void setHouse(Byte house) {
		this.house = house;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.car
	 * @return  the value of t_user_info.car
	 * @mbg.generated
	 */
	public Byte getCar() {
		return car;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.car
	 * @param car  the value for t_user_info.car
	 * @mbg.generated
	 */
	public void setCar(Byte car) {
		this.car = car;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.emergency_contact_type
	 * @return  the value of t_user_info.emergency_contact_type
	 * @mbg.generated
	 */
	public Byte getEmergencyContactType() {
		return emergencyContactType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.emergency_contact_type
	 * @param emergencyContactType  the value for t_user_info.emergency_contact_type
	 * @mbg.generated
	 */
	public void setEmergencyContactType(Byte emergencyContactType) {
		this.emergencyContactType = emergencyContactType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.emergency_contact_name
	 * @return  the value of t_user_info.emergency_contact_name
	 * @mbg.generated
	 */
	public String getEmergencyContactName() {
		return emergencyContactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.emergency_contact_name
	 * @param emergencyContactName  the value for t_user_info.emergency_contact_name
	 * @mbg.generated
	 */
	public void setEmergencyContactName(String emergencyContactName) {
		this.emergencyContactName = emergencyContactName == null ? null : emergencyContactName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.emergency_contact_mobile
	 * @return  the value of t_user_info.emergency_contact_mobile
	 * @mbg.generated
	 */
	public String getEmergencyContactMobile() {
		return emergencyContactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.emergency_contact_mobile
	 * @param emergencyContactMobile  the value for t_user_info.emergency_contact_mobile
	 * @mbg.generated
	 */
	public void setEmergencyContactMobile(String emergencyContactMobile) {
		this.emergencyContactMobile = emergencyContactMobile == null ? null : emergencyContactMobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.member_type
	 * @return  the value of t_user_info.member_type
	 * @mbg.generated
	 */
	public Boolean getMemberType() {
		return memberType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.member_type
	 * @param memberType  the value for t_user_info.member_type
	 * @mbg.generated
	 */
	public void setMemberType(Boolean memberType) {
		this.memberType = memberType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.loan_member_time
	 * @return  the value of t_user_info.loan_member_time
	 * @mbg.generated
	 */
	public Date getLoanMemberTime() {
		return loanMemberTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.loan_member_time
	 * @param loanMemberTime  the value for t_user_info.loan_member_time
	 * @mbg.generated
	 */
	public void setLoanMemberTime(Date loanMemberTime) {
		this.loanMemberTime = loanMemberTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.invest_member_time
	 * @return  the value of t_user_info.invest_member_time
	 * @mbg.generated
	 */
	public Date getInvestMemberTime() {
		return investMemberTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.invest_member_time
	 * @param investMemberTime  the value for t_user_info.invest_member_time
	 * @mbg.generated
	 */
	public void setInvestMemberTime(Date investMemberTime) {
		this.investMemberTime = investMemberTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.add_base_info_schedule
	 * @return  the value of t_user_info.add_base_info_schedule
	 * @mbg.generated
	 */
	public Byte getAddBaseInfoSchedule() {
		return addBaseInfoSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.add_base_info_schedule
	 * @param addBaseInfoSchedule  the value for t_user_info.add_base_info_schedule
	 * @mbg.generated
	 */
	public void setAddBaseInfoSchedule(Byte addBaseInfoSchedule) {
		this.addBaseInfoSchedule = addBaseInfoSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.business_code
	 * @return  the value of t_user_info.business_code
	 * @mbg.generated
	 */
	public String getBusinessCode() {
		return businessCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.business_code
	 * @param businessCode  the value for t_user_info.business_code
	 * @mbg.generated
	 */
	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode == null ? null : businessCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user_info.enterprise_name
	 * @return  the value of t_user_info.enterprise_name
	 * @mbg.generated
	 */
	public String getEnterpriseName() {
		return enterpriseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user_info.enterprise_name
	 * @param enterpriseName  the value for t_user_info.enterprise_name
	 * @mbg.generated
	 */
	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
	}
}