package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Auditsubject;
import java.util.List;

public interface AuditsubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audit_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audit_subject
     *
     * @mbg.generated
     */
    int insert(Auditsubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audit_subject
     *
     * @mbg.generated
     */
    Auditsubject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audit_subject
     *
     * @mbg.generated
     */
    List<Auditsubject> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_audit_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Auditsubject record);
}