package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Massemail;
import java.util.List;

public interface MassemailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email
     *
     * @mbg.generated
     */
    int insert(Massemail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email
     *
     * @mbg.generated
     */
    Massemail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email
     *
     * @mbg.generated
     */
    List<Massemail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mass_email
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Massemail record);
}