package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Paymentrequest;
import java.util.List;

public interface PaymentrequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_request
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_request
     *
     * @mbg.generated
     */
    int insert(Paymentrequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_request
     *
     * @mbg.generated
     */
    Paymentrequest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_request
     *
     * @mbg.generated
     */
    List<Paymentrequest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_request
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Paymentrequest record);
}