package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Redpacketuser;
import java.util.List;

public interface RedpacketuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packet_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packet_user
     *
     * @mbg.generated
     */
    int insert(Redpacketuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packet_user
     *
     * @mbg.generated
     */
    Redpacketuser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packet_user
     *
     * @mbg.generated
     */
    List<Redpacketuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_red_packet_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Redpacketuser record);
}