package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Smssending;
import java.util.List;

public interface SmssendingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_sending
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_sending
     *
     * @mbg.generated
     */
    int insert(Smssending record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_sending
     *
     * @mbg.generated
     */
    Smssending selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_sending
     *
     * @mbg.generated
     */
    List<Smssending> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_sending
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Smssending record);
}