package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Templatenotice;
import java.util.List;

public interface TemplatenoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_notice
     *
     * @mbg.generated
     */
    int insert(Templatenotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_notice
     *
     * @mbg.generated
     */
    Templatenotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_notice
     *
     * @mbg.generated
     */
    List<Templatenotice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_template_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Templatenotice record);
}