package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Wealthcircleuser;
import java.util.List;

public interface WealthcircleuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wealthcircle_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wealthcircle_user
     *
     * @mbg.generated
     */
    int insert(Wealthcircleuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wealthcircle_user
     *
     * @mbg.generated
     */
    Wealthcircleuser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wealthcircle_user
     *
     * @mbg.generated
     */
    List<Wealthcircleuser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wealthcircle_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wealthcircleuser record);
}