package cn.liuxingwei.spring.boot.mapper;

import cn.liuxingwei.spring.boot.model.Wechatmenu;
import java.util.List;

public interface WechatmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_menu
     *
     * @mbg.generated
     */
    int insert(Wechatmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_menu
     *
     * @mbg.generated
     */
    Wechatmenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_menu
     *
     * @mbg.generated
     */
    List<Wechatmenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_wechat_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wechatmenu record);
}