package com.juqijinfu.p2p.platform.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bid
 */
public class Bid {

	/**
	 * Database Column Remarks: 借款标id This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 发布时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 借款人ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 所属借款产品ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.product_id
	 * @mbg.generated
	 */
	private Long productId;
	/**
	 * Database Column Remarks: 借款标题 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * Database Column Remarks: 借款金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.amount
	 * @mbg.generated
	 */
	private BigDecimal amount;
	/**
	 * Database Column Remarks: 年利率 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.apr
	 * @mbg.generated
	 */
	private BigDecimal apr;
	/**
	 * Database Column Remarks: 借款期限单位。1:天;2:月 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.period_unit
	 * @mbg.generated
	 */
	private Byte periodUnit;
	/**
	 * Database Column Remarks: 借款期限 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.period
	 * @mbg.generated
	 */
	private Integer period;
	/**
	 * Database Column Remarks: 借款服务费 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.loan_fee
	 * @mbg.generated
	 */
	private BigDecimal loanFee;
	/**
	 * Database Column Remarks: 借款服务费左边的部分(计算公式加号左边的) This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.loan_fee_left
	 * @mbg.generated
	 */
	private BigDecimal loanFeeLeft;
	/**
	 * Database Column Remarks: 借款服务费右边的部分(计算公式加号右边的) This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.loan_fee_right
	 * @mbg.generated
	 */
	private BigDecimal loanFeeRight;
	/**
	 * Database Column Remarks: 借款服务费、理财服务费、逾期罚息规则（以JSON串的形式存储）(数据来自借款产品) This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.service_fee_rule
	 * @mbg.generated
	 */
	private String serviceFeeRule;
	/**
	 * Database Column Remarks: 还款方式 1-先息后本 2-等本等息 3-一次性还款 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.repayment_type
	 * @mbg.generated
	 */
	private Byte repaymentType;
	/**
	 * Database Column Remarks: 购买方式 1-按金额 2-按份数(数据来自借款产品) This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.buy_type
	 * @mbg.generated
	 */
	private Byte buyType;
	/**
	 * Database Column Remarks: 借款描述 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.description
	 * @mbg.generated
	 */
	private String description;
	/**
	 * Database Column Remarks: 标的状态： 0-初审中； 1-借款中（初审通过）; 2-复审待审（已满标）； 3-待放款（复审通过）； 4-还款中（财务已放款）; 5-已还款； -1-初审不通过； -2-复审不通过； -3-流标（固定期限内没有满标，系统执行流标）； This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 标的发布入口: 1-pc  2-android  3-ios  4-wechat  This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.client
	 * @mbg.generated
	 */
	private Byte client;
	/**
	 * Database Column Remarks: 投标期限。单位固定：天 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.invest_period
	 * @mbg.generated
	 */
	private Integer investPeriod;
	/**
	 * Database Column Remarks: 按份数购买：每份的金额； 按金额购买：起投金额。 (数据来自借款产品） This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.min_invest_amount
	 * @mbg.generated
	 */
	private BigDecimal minInvestAmount;
	/**
	 * Database Column Remarks: 拆分份数 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.invest_copies
	 * @mbg.generated
	 */
	private Integer investCopies;
	/**
	 * Database Column Remarks: 保证金 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.bail
	 * @mbg.generated
	 */
	private BigDecimal bail;
	/**
	 * Database Column Remarks: 预发布时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.pre_release_time
	 * @mbg.generated
	 */
	private Date preReleaseTime;
	/**
	 * Database Column Remarks: 满标时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.invest_expire_time
	 * @mbg.generated
	 */
	private Date investExpireTime;
	/**
	 * Database Column Remarks: 实际满标时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.real_invest_expire_time
	 * @mbg.generated
	 */
	private Date realInvestExpireTime;
	/**
	 * Database Column Remarks: 借款进度比例 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.loan_schedule
	 * @mbg.generated
	 */
	private BigDecimal loanSchedule;
	/**
	 * Database Column Remarks: 已投总额(冗余) This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.has_invested_amount
	 * @mbg.generated
	 */
	private BigDecimal hasInvestedAmount;
	/**
	 * Database Column Remarks: 加入人次 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.invest_count
	 * @mbg.generated
	 */
	private Integer investCount;
	/**
	 * Database Column Remarks: 初审审核人 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.preauditor_supervisor_id
	 * @mbg.generated
	 */
	private Long preauditorSupervisorId;
	/**
	 * Database Column Remarks: 初审时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.preaudit_time
	 * @mbg.generated
	 */
	private Date preauditTime;
	/**
	 * Database Column Remarks: 审核意见 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.preaudit_suggest
	 * @mbg.generated
	 */
	private String preauditSuggest;
	/**
	 * Database Column Remarks: 复审审核人ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.auditor_supervisor_id
	 * @mbg.generated
	 */
	private Long auditorSupervisorId;
	/**
	 * Database Column Remarks: 复审时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.audit_time
	 * @mbg.generated
	 */
	private Date auditTime;
	/**
	 * Database Column Remarks: 复审意见 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.audit_suggest
	 * @mbg.generated
	 */
	private String auditSuggest;
	/**
	 * Database Column Remarks: 放款人ID This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.release_supervisor_id
	 * @mbg.generated
	 */
	private Long releaseSupervisorId;
	/**
	 * Database Column Remarks: 放款时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.release_time
	 * @mbg.generated
	 */
	private Date releaseTime;
	/**
	 * Database Column Remarks: 最后还款时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.last_repay_time
	 * @mbg.generated
	 */
	private Date lastRepayTime;
	/**
	 * Database Column Remarks: 标的编号：资金托管用，借款标唯一标识 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.mer_bid_no
	 * @mbg.generated
	 */
	private String merBidNo;
	/**
	 * Database Column Remarks: 业务订单号，标的登记操作唯一标识 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.service_order_no
	 * @mbg.generated
	 */
	private String serviceOrderNo;
	/**
	 * Database Column Remarks: 托管方返回订单号 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.trust_order_no
	 * @mbg.generated
	 */
	private String trustOrderNo;
	/**
	 * Database Column Remarks: 奖励发放状态 0 未发放 1 cps已发放 2 财富圈已发放 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.reward_grant_type
	 * @mbg.generated
	 */
	private Byte rewardGrantType;
	/**
	 * Database Column Remarks: 企业名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.enterprise_name
	 * @mbg.generated
	 */
	private String enterpriseName;
	/**
	 * Database Column Remarks: 所属行业 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.industry
	 * @mbg.generated
	 */
	private String industry;
	/**
	 * Database Column Remarks: 成立日期，单位年 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.establish_date
	 * @mbg.generated
	 */
	private Integer establishDate;
	/**
	 * Database Column Remarks: 注册资本，单位万元 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.register_capital
	 * @mbg.generated
	 */
	private Integer registerCapital;
	/**
	 * Database Column Remarks: 企业规模 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.scale
	 * @mbg.generated
	 */
	private String scale;
	/**
	 * Database Column Remarks: 主营业务 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.main_business
	 * @mbg.generated
	 */
	private String mainBusiness;
	/**
	 * Database Column Remarks: 水印名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.watermark_name
	 * @mbg.generated
	 */
	private String watermarkName;
	/**
	 * Database Column Remarks: 关联名单库id，由于可能关联多份名单，因此使用varchar类型，以英文逗号分隔 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.name_list_id
	 * @mbg.generated
	 */
	private String nameListId;
	/**
	 * Database Column Remarks: 0,线上标。1，线下标 This field was generated by MyBatis Generator. This field corresponds to the database column t_bid.loan_type
	 * @mbg.generated
	 */
	private Byte loanType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.id
	 * @return  the value of t_bid.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.id
	 * @param id  the value for t_bid.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.time
	 * @return  the value of t_bid.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.time
	 * @param time  the value for t_bid.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.user_id
	 * @return  the value of t_bid.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.user_id
	 * @param userId  the value for t_bid.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.product_id
	 * @return  the value of t_bid.product_id
	 * @mbg.generated
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.product_id
	 * @param productId  the value for t_bid.product_id
	 * @mbg.generated
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.title
	 * @return  the value of t_bid.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.title
	 * @param title  the value for t_bid.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.amount
	 * @return  the value of t_bid.amount
	 * @mbg.generated
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.amount
	 * @param amount  the value for t_bid.amount
	 * @mbg.generated
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.apr
	 * @return  the value of t_bid.apr
	 * @mbg.generated
	 */
	public BigDecimal getApr() {
		return apr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.apr
	 * @param apr  the value for t_bid.apr
	 * @mbg.generated
	 */
	public void setApr(BigDecimal apr) {
		this.apr = apr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.period_unit
	 * @return  the value of t_bid.period_unit
	 * @mbg.generated
	 */
	public Byte getPeriodUnit() {
		return periodUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.period_unit
	 * @param periodUnit  the value for t_bid.period_unit
	 * @mbg.generated
	 */
	public void setPeriodUnit(Byte periodUnit) {
		this.periodUnit = periodUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.period
	 * @return  the value of t_bid.period
	 * @mbg.generated
	 */
	public Integer getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.period
	 * @param period  the value for t_bid.period
	 * @mbg.generated
	 */
	public void setPeriod(Integer period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.loan_fee
	 * @return  the value of t_bid.loan_fee
	 * @mbg.generated
	 */
	public BigDecimal getLoanFee() {
		return loanFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.loan_fee
	 * @param loanFee  the value for t_bid.loan_fee
	 * @mbg.generated
	 */
	public void setLoanFee(BigDecimal loanFee) {
		this.loanFee = loanFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.loan_fee_left
	 * @return  the value of t_bid.loan_fee_left
	 * @mbg.generated
	 */
	public BigDecimal getLoanFeeLeft() {
		return loanFeeLeft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.loan_fee_left
	 * @param loanFeeLeft  the value for t_bid.loan_fee_left
	 * @mbg.generated
	 */
	public void setLoanFeeLeft(BigDecimal loanFeeLeft) {
		this.loanFeeLeft = loanFeeLeft;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.loan_fee_right
	 * @return  the value of t_bid.loan_fee_right
	 * @mbg.generated
	 */
	public BigDecimal getLoanFeeRight() {
		return loanFeeRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.loan_fee_right
	 * @param loanFeeRight  the value for t_bid.loan_fee_right
	 * @mbg.generated
	 */
	public void setLoanFeeRight(BigDecimal loanFeeRight) {
		this.loanFeeRight = loanFeeRight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.service_fee_rule
	 * @return  the value of t_bid.service_fee_rule
	 * @mbg.generated
	 */
	public String getServiceFeeRule() {
		return serviceFeeRule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.service_fee_rule
	 * @param serviceFeeRule  the value for t_bid.service_fee_rule
	 * @mbg.generated
	 */
	public void setServiceFeeRule(String serviceFeeRule) {
		this.serviceFeeRule = serviceFeeRule == null ? null : serviceFeeRule.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.repayment_type
	 * @return  the value of t_bid.repayment_type
	 * @mbg.generated
	 */
	public Byte getRepaymentType() {
		return repaymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.repayment_type
	 * @param repaymentType  the value for t_bid.repayment_type
	 * @mbg.generated
	 */
	public void setRepaymentType(Byte repaymentType) {
		this.repaymentType = repaymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.buy_type
	 * @return  the value of t_bid.buy_type
	 * @mbg.generated
	 */
	public Byte getBuyType() {
		return buyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.buy_type
	 * @param buyType  the value for t_bid.buy_type
	 * @mbg.generated
	 */
	public void setBuyType(Byte buyType) {
		this.buyType = buyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.description
	 * @return  the value of t_bid.description
	 * @mbg.generated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.description
	 * @param description  the value for t_bid.description
	 * @mbg.generated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.status
	 * @return  the value of t_bid.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.status
	 * @param status  the value for t_bid.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.client
	 * @return  the value of t_bid.client
	 * @mbg.generated
	 */
	public Byte getClient() {
		return client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.client
	 * @param client  the value for t_bid.client
	 * @mbg.generated
	 */
	public void setClient(Byte client) {
		this.client = client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.invest_period
	 * @return  the value of t_bid.invest_period
	 * @mbg.generated
	 */
	public Integer getInvestPeriod() {
		return investPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.invest_period
	 * @param investPeriod  the value for t_bid.invest_period
	 * @mbg.generated
	 */
	public void setInvestPeriod(Integer investPeriod) {
		this.investPeriod = investPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.min_invest_amount
	 * @return  the value of t_bid.min_invest_amount
	 * @mbg.generated
	 */
	public BigDecimal getMinInvestAmount() {
		return minInvestAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.min_invest_amount
	 * @param minInvestAmount  the value for t_bid.min_invest_amount
	 * @mbg.generated
	 */
	public void setMinInvestAmount(BigDecimal minInvestAmount) {
		this.minInvestAmount = minInvestAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.invest_copies
	 * @return  the value of t_bid.invest_copies
	 * @mbg.generated
	 */
	public Integer getInvestCopies() {
		return investCopies;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.invest_copies
	 * @param investCopies  the value for t_bid.invest_copies
	 * @mbg.generated
	 */
	public void setInvestCopies(Integer investCopies) {
		this.investCopies = investCopies;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.bail
	 * @return  the value of t_bid.bail
	 * @mbg.generated
	 */
	public BigDecimal getBail() {
		return bail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.bail
	 * @param bail  the value for t_bid.bail
	 * @mbg.generated
	 */
	public void setBail(BigDecimal bail) {
		this.bail = bail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.pre_release_time
	 * @return  the value of t_bid.pre_release_time
	 * @mbg.generated
	 */
	public Date getPreReleaseTime() {
		return preReleaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.pre_release_time
	 * @param preReleaseTime  the value for t_bid.pre_release_time
	 * @mbg.generated
	 */
	public void setPreReleaseTime(Date preReleaseTime) {
		this.preReleaseTime = preReleaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.invest_expire_time
	 * @return  the value of t_bid.invest_expire_time
	 * @mbg.generated
	 */
	public Date getInvestExpireTime() {
		return investExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.invest_expire_time
	 * @param investExpireTime  the value for t_bid.invest_expire_time
	 * @mbg.generated
	 */
	public void setInvestExpireTime(Date investExpireTime) {
		this.investExpireTime = investExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.real_invest_expire_time
	 * @return  the value of t_bid.real_invest_expire_time
	 * @mbg.generated
	 */
	public Date getRealInvestExpireTime() {
		return realInvestExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.real_invest_expire_time
	 * @param realInvestExpireTime  the value for t_bid.real_invest_expire_time
	 * @mbg.generated
	 */
	public void setRealInvestExpireTime(Date realInvestExpireTime) {
		this.realInvestExpireTime = realInvestExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.loan_schedule
	 * @return  the value of t_bid.loan_schedule
	 * @mbg.generated
	 */
	public BigDecimal getLoanSchedule() {
		return loanSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.loan_schedule
	 * @param loanSchedule  the value for t_bid.loan_schedule
	 * @mbg.generated
	 */
	public void setLoanSchedule(BigDecimal loanSchedule) {
		this.loanSchedule = loanSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.has_invested_amount
	 * @return  the value of t_bid.has_invested_amount
	 * @mbg.generated
	 */
	public BigDecimal getHasInvestedAmount() {
		return hasInvestedAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.has_invested_amount
	 * @param hasInvestedAmount  the value for t_bid.has_invested_amount
	 * @mbg.generated
	 */
	public void setHasInvestedAmount(BigDecimal hasInvestedAmount) {
		this.hasInvestedAmount = hasInvestedAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.invest_count
	 * @return  the value of t_bid.invest_count
	 * @mbg.generated
	 */
	public Integer getInvestCount() {
		return investCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.invest_count
	 * @param investCount  the value for t_bid.invest_count
	 * @mbg.generated
	 */
	public void setInvestCount(Integer investCount) {
		this.investCount = investCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.preauditor_supervisor_id
	 * @return  the value of t_bid.preauditor_supervisor_id
	 * @mbg.generated
	 */
	public Long getPreauditorSupervisorId() {
		return preauditorSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.preauditor_supervisor_id
	 * @param preauditorSupervisorId  the value for t_bid.preauditor_supervisor_id
	 * @mbg.generated
	 */
	public void setPreauditorSupervisorId(Long preauditorSupervisorId) {
		this.preauditorSupervisorId = preauditorSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.preaudit_time
	 * @return  the value of t_bid.preaudit_time
	 * @mbg.generated
	 */
	public Date getPreauditTime() {
		return preauditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.preaudit_time
	 * @param preauditTime  the value for t_bid.preaudit_time
	 * @mbg.generated
	 */
	public void setPreauditTime(Date preauditTime) {
		this.preauditTime = preauditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.preaudit_suggest
	 * @return  the value of t_bid.preaudit_suggest
	 * @mbg.generated
	 */
	public String getPreauditSuggest() {
		return preauditSuggest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.preaudit_suggest
	 * @param preauditSuggest  the value for t_bid.preaudit_suggest
	 * @mbg.generated
	 */
	public void setPreauditSuggest(String preauditSuggest) {
		this.preauditSuggest = preauditSuggest == null ? null : preauditSuggest.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.auditor_supervisor_id
	 * @return  the value of t_bid.auditor_supervisor_id
	 * @mbg.generated
	 */
	public Long getAuditorSupervisorId() {
		return auditorSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.auditor_supervisor_id
	 * @param auditorSupervisorId  the value for t_bid.auditor_supervisor_id
	 * @mbg.generated
	 */
	public void setAuditorSupervisorId(Long auditorSupervisorId) {
		this.auditorSupervisorId = auditorSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.audit_time
	 * @return  the value of t_bid.audit_time
	 * @mbg.generated
	 */
	public Date getAuditTime() {
		return auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.audit_time
	 * @param auditTime  the value for t_bid.audit_time
	 * @mbg.generated
	 */
	public void setAuditTime(Date auditTime) {
		this.auditTime = auditTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.audit_suggest
	 * @return  the value of t_bid.audit_suggest
	 * @mbg.generated
	 */
	public String getAuditSuggest() {
		return auditSuggest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.audit_suggest
	 * @param auditSuggest  the value for t_bid.audit_suggest
	 * @mbg.generated
	 */
	public void setAuditSuggest(String auditSuggest) {
		this.auditSuggest = auditSuggest == null ? null : auditSuggest.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.release_supervisor_id
	 * @return  the value of t_bid.release_supervisor_id
	 * @mbg.generated
	 */
	public Long getReleaseSupervisorId() {
		return releaseSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.release_supervisor_id
	 * @param releaseSupervisorId  the value for t_bid.release_supervisor_id
	 * @mbg.generated
	 */
	public void setReleaseSupervisorId(Long releaseSupervisorId) {
		this.releaseSupervisorId = releaseSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.release_time
	 * @return  the value of t_bid.release_time
	 * @mbg.generated
	 */
	public Date getReleaseTime() {
		return releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.release_time
	 * @param releaseTime  the value for t_bid.release_time
	 * @mbg.generated
	 */
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.last_repay_time
	 * @return  the value of t_bid.last_repay_time
	 * @mbg.generated
	 */
	public Date getLastRepayTime() {
		return lastRepayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.last_repay_time
	 * @param lastRepayTime  the value for t_bid.last_repay_time
	 * @mbg.generated
	 */
	public void setLastRepayTime(Date lastRepayTime) {
		this.lastRepayTime = lastRepayTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.mer_bid_no
	 * @return  the value of t_bid.mer_bid_no
	 * @mbg.generated
	 */
	public String getMerBidNo() {
		return merBidNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.mer_bid_no
	 * @param merBidNo  the value for t_bid.mer_bid_no
	 * @mbg.generated
	 */
	public void setMerBidNo(String merBidNo) {
		this.merBidNo = merBidNo == null ? null : merBidNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.service_order_no
	 * @return  the value of t_bid.service_order_no
	 * @mbg.generated
	 */
	public String getServiceOrderNo() {
		return serviceOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.service_order_no
	 * @param serviceOrderNo  the value for t_bid.service_order_no
	 * @mbg.generated
	 */
	public void setServiceOrderNo(String serviceOrderNo) {
		this.serviceOrderNo = serviceOrderNo == null ? null : serviceOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.trust_order_no
	 * @return  the value of t_bid.trust_order_no
	 * @mbg.generated
	 */
	public String getTrustOrderNo() {
		return trustOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.trust_order_no
	 * @param trustOrderNo  the value for t_bid.trust_order_no
	 * @mbg.generated
	 */
	public void setTrustOrderNo(String trustOrderNo) {
		this.trustOrderNo = trustOrderNo == null ? null : trustOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.reward_grant_type
	 * @return  the value of t_bid.reward_grant_type
	 * @mbg.generated
	 */
	public Byte getRewardGrantType() {
		return rewardGrantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.reward_grant_type
	 * @param rewardGrantType  the value for t_bid.reward_grant_type
	 * @mbg.generated
	 */
	public void setRewardGrantType(Byte rewardGrantType) {
		this.rewardGrantType = rewardGrantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.enterprise_name
	 * @return  the value of t_bid.enterprise_name
	 * @mbg.generated
	 */
	public String getEnterpriseName() {
		return enterpriseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.enterprise_name
	 * @param enterpriseName  the value for t_bid.enterprise_name
	 * @mbg.generated
	 */
	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.industry
	 * @return  the value of t_bid.industry
	 * @mbg.generated
	 */
	public String getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.industry
	 * @param industry  the value for t_bid.industry
	 * @mbg.generated
	 */
	public void setIndustry(String industry) {
		this.industry = industry == null ? null : industry.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.establish_date
	 * @return  the value of t_bid.establish_date
	 * @mbg.generated
	 */
	public Integer getEstablishDate() {
		return establishDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.establish_date
	 * @param establishDate  the value for t_bid.establish_date
	 * @mbg.generated
	 */
	public void setEstablishDate(Integer establishDate) {
		this.establishDate = establishDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.register_capital
	 * @return  the value of t_bid.register_capital
	 * @mbg.generated
	 */
	public Integer getRegisterCapital() {
		return registerCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.register_capital
	 * @param registerCapital  the value for t_bid.register_capital
	 * @mbg.generated
	 */
	public void setRegisterCapital(Integer registerCapital) {
		this.registerCapital = registerCapital;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.scale
	 * @return  the value of t_bid.scale
	 * @mbg.generated
	 */
	public String getScale() {
		return scale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.scale
	 * @param scale  the value for t_bid.scale
	 * @mbg.generated
	 */
	public void setScale(String scale) {
		this.scale = scale == null ? null : scale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.main_business
	 * @return  the value of t_bid.main_business
	 * @mbg.generated
	 */
	public String getMainBusiness() {
		return mainBusiness;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.main_business
	 * @param mainBusiness  the value for t_bid.main_business
	 * @mbg.generated
	 */
	public void setMainBusiness(String mainBusiness) {
		this.mainBusiness = mainBusiness == null ? null : mainBusiness.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.watermark_name
	 * @return  the value of t_bid.watermark_name
	 * @mbg.generated
	 */
	public String getWatermarkName() {
		return watermarkName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.watermark_name
	 * @param watermarkName  the value for t_bid.watermark_name
	 * @mbg.generated
	 */
	public void setWatermarkName(String watermarkName) {
		this.watermarkName = watermarkName == null ? null : watermarkName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.name_list_id
	 * @return  the value of t_bid.name_list_id
	 * @mbg.generated
	 */
	public String getNameListId() {
		return nameListId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.name_list_id
	 * @param nameListId  the value for t_bid.name_list_id
	 * @mbg.generated
	 */
	public void setNameListId(String nameListId) {
		this.nameListId = nameListId == null ? null : nameListId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bid.loan_type
	 * @return  the value of t_bid.loan_type
	 * @mbg.generated
	 */
	public Byte getLoanType() {
		return loanType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bid.loan_type
	 * @param loanType  the value for t_bid.loan_type
	 * @mbg.generated
	 */
	public void setLoanType(Byte loanType) {
		this.loanType = loanType;
	}
}