package com.juqijinfu.p2p.platform.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_debt_transfer
 */
public class Debttransfer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 对应的投资id This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.invest_id
	 * @mbg.generated
	 */
	private Long investId;
	/**
	 * Database Column Remarks: 转让人的user_id This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 转让标题 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.title
	 * @mbg.generated
	 */
	private String title;
	/**
	 * Database Column Remarks: 债权金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.debt_amount
	 * @mbg.generated
	 */
	private BigDecimal debtAmount;
	/**
	 * Database Column Remarks: 债权本金 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.debt_principal
	 * @mbg.generated
	 */
	private BigDecimal debtPrincipal;
	/**
	 * Database Column Remarks: 转让底价 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.transfer_price
	 * @mbg.generated
	 */
	private BigDecimal transferPrice;
	/**
	 * Database Column Remarks: 转让期数 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.transfer_period
	 * @mbg.generated
	 */
	private Integer transferPeriod;
	/**
	 * Database Column Remarks: 转让期限(从审核通过算，单位天) This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.period
	 * @mbg.generated
	 */
	private Byte period;
	/**
	 * Database Column Remarks: 状态 0-待审核； 1-转让中； 3-成功； -1-审核不通过； -2-过期； -3-失效。 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 审核管理员id This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.audit_supervisor_id
	 * @mbg.generated
	 */
	private Long auditSupervisorId;
	/**
	 * Database Column Remarks: 审核通过时间(开始竞拍时间) This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.start_time
	 * @mbg.generated
	 */
	private Date startTime;
	/**
	 * Database Column Remarks: 转让到期时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.end_time
	 * @mbg.generated
	 */
	private Date endTime;
	/**
	 * Database Column Remarks: 成交者 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.transaction_user_id
	 * @mbg.generated
	 */
	private Long transactionUserId;
	/**
	 * Database Column Remarks: 成交时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.transaction_time
	 * @mbg.generated
	 */
	private Date transactionTime;
	/**
	 * Database Column Remarks: 成交价 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.transaction_price
	 * @mbg.generated
	 */
	private BigDecimal transactionPrice;
	/**
	 * Database Column Remarks: 业务订单号 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.service_order_no
	 * @mbg.generated
	 */
	private String serviceOrderNo;
	/**
	 * Database Column Remarks: 交易订单号(第三方返回) This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.trust_order_no
	 * @mbg.generated
	 */
	private String trustOrderNo;
	/**
	 * Database Column Remarks: 普通标，债权标可投金额  U计划为已投金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.tranfer_amount
	 * @mbg.generated
	 */
	private BigDecimal tranferAmount;
	/**
	 * Database Column Remarks: 0，普通标，1，债权标 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.tranfer_type
	 * @mbg.generated
	 */
	private Byte tranferType;
	/**
	 * Database Column Remarks: 预售时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.pre_release_time
	 * @mbg.generated
	 */
	private Date preReleaseTime;
	/**
	 * Database Column Remarks: 转让进度 This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.schedule
	 * @mbg.generated
	 */
	private BigDecimal schedule;
	/**
	 * Database Column Remarks: 理财计划记录ID This field was generated by MyBatis Generator. This field corresponds to the database column t_debt_transfer.project_invest_id
	 * @mbg.generated
	 */
	private Long projectInvestId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.id
	 * @return  the value of t_debt_transfer.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.id
	 * @param id  the value for t_debt_transfer.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.time
	 * @return  the value of t_debt_transfer.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.time
	 * @param time  the value for t_debt_transfer.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.invest_id
	 * @return  the value of t_debt_transfer.invest_id
	 * @mbg.generated
	 */
	public Long getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.invest_id
	 * @param investId  the value for t_debt_transfer.invest_id
	 * @mbg.generated
	 */
	public void setInvestId(Long investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.user_id
	 * @return  the value of t_debt_transfer.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.user_id
	 * @param userId  the value for t_debt_transfer.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.title
	 * @return  the value of t_debt_transfer.title
	 * @mbg.generated
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.title
	 * @param title  the value for t_debt_transfer.title
	 * @mbg.generated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.debt_amount
	 * @return  the value of t_debt_transfer.debt_amount
	 * @mbg.generated
	 */
	public BigDecimal getDebtAmount() {
		return debtAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.debt_amount
	 * @param debtAmount  the value for t_debt_transfer.debt_amount
	 * @mbg.generated
	 */
	public void setDebtAmount(BigDecimal debtAmount) {
		this.debtAmount = debtAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.debt_principal
	 * @return  the value of t_debt_transfer.debt_principal
	 * @mbg.generated
	 */
	public BigDecimal getDebtPrincipal() {
		return debtPrincipal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.debt_principal
	 * @param debtPrincipal  the value for t_debt_transfer.debt_principal
	 * @mbg.generated
	 */
	public void setDebtPrincipal(BigDecimal debtPrincipal) {
		this.debtPrincipal = debtPrincipal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.transfer_price
	 * @return  the value of t_debt_transfer.transfer_price
	 * @mbg.generated
	 */
	public BigDecimal getTransferPrice() {
		return transferPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.transfer_price
	 * @param transferPrice  the value for t_debt_transfer.transfer_price
	 * @mbg.generated
	 */
	public void setTransferPrice(BigDecimal transferPrice) {
		this.transferPrice = transferPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.transfer_period
	 * @return  the value of t_debt_transfer.transfer_period
	 * @mbg.generated
	 */
	public Integer getTransferPeriod() {
		return transferPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.transfer_period
	 * @param transferPeriod  the value for t_debt_transfer.transfer_period
	 * @mbg.generated
	 */
	public void setTransferPeriod(Integer transferPeriod) {
		this.transferPeriod = transferPeriod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.period
	 * @return  the value of t_debt_transfer.period
	 * @mbg.generated
	 */
	public Byte getPeriod() {
		return period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.period
	 * @param period  the value for t_debt_transfer.period
	 * @mbg.generated
	 */
	public void setPeriod(Byte period) {
		this.period = period;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.status
	 * @return  the value of t_debt_transfer.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.status
	 * @param status  the value for t_debt_transfer.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.audit_supervisor_id
	 * @return  the value of t_debt_transfer.audit_supervisor_id
	 * @mbg.generated
	 */
	public Long getAuditSupervisorId() {
		return auditSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.audit_supervisor_id
	 * @param auditSupervisorId  the value for t_debt_transfer.audit_supervisor_id
	 * @mbg.generated
	 */
	public void setAuditSupervisorId(Long auditSupervisorId) {
		this.auditSupervisorId = auditSupervisorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.start_time
	 * @return  the value of t_debt_transfer.start_time
	 * @mbg.generated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.start_time
	 * @param startTime  the value for t_debt_transfer.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.end_time
	 * @return  the value of t_debt_transfer.end_time
	 * @mbg.generated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.end_time
	 * @param endTime  the value for t_debt_transfer.end_time
	 * @mbg.generated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.transaction_user_id
	 * @return  the value of t_debt_transfer.transaction_user_id
	 * @mbg.generated
	 */
	public Long getTransactionUserId() {
		return transactionUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.transaction_user_id
	 * @param transactionUserId  the value for t_debt_transfer.transaction_user_id
	 * @mbg.generated
	 */
	public void setTransactionUserId(Long transactionUserId) {
		this.transactionUserId = transactionUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.transaction_time
	 * @return  the value of t_debt_transfer.transaction_time
	 * @mbg.generated
	 */
	public Date getTransactionTime() {
		return transactionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.transaction_time
	 * @param transactionTime  the value for t_debt_transfer.transaction_time
	 * @mbg.generated
	 */
	public void setTransactionTime(Date transactionTime) {
		this.transactionTime = transactionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.transaction_price
	 * @return  the value of t_debt_transfer.transaction_price
	 * @mbg.generated
	 */
	public BigDecimal getTransactionPrice() {
		return transactionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.transaction_price
	 * @param transactionPrice  the value for t_debt_transfer.transaction_price
	 * @mbg.generated
	 */
	public void setTransactionPrice(BigDecimal transactionPrice) {
		this.transactionPrice = transactionPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.service_order_no
	 * @return  the value of t_debt_transfer.service_order_no
	 * @mbg.generated
	 */
	public String getServiceOrderNo() {
		return serviceOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.service_order_no
	 * @param serviceOrderNo  the value for t_debt_transfer.service_order_no
	 * @mbg.generated
	 */
	public void setServiceOrderNo(String serviceOrderNo) {
		this.serviceOrderNo = serviceOrderNo == null ? null : serviceOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.trust_order_no
	 * @return  the value of t_debt_transfer.trust_order_no
	 * @mbg.generated
	 */
	public String getTrustOrderNo() {
		return trustOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.trust_order_no
	 * @param trustOrderNo  the value for t_debt_transfer.trust_order_no
	 * @mbg.generated
	 */
	public void setTrustOrderNo(String trustOrderNo) {
		this.trustOrderNo = trustOrderNo == null ? null : trustOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.tranfer_amount
	 * @return  the value of t_debt_transfer.tranfer_amount
	 * @mbg.generated
	 */
	public BigDecimal getTranferAmount() {
		return tranferAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.tranfer_amount
	 * @param tranferAmount  the value for t_debt_transfer.tranfer_amount
	 * @mbg.generated
	 */
	public void setTranferAmount(BigDecimal tranferAmount) {
		this.tranferAmount = tranferAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.tranfer_type
	 * @return  the value of t_debt_transfer.tranfer_type
	 * @mbg.generated
	 */
	public Byte getTranferType() {
		return tranferType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.tranfer_type
	 * @param tranferType  the value for t_debt_transfer.tranfer_type
	 * @mbg.generated
	 */
	public void setTranferType(Byte tranferType) {
		this.tranferType = tranferType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.pre_release_time
	 * @return  the value of t_debt_transfer.pre_release_time
	 * @mbg.generated
	 */
	public Date getPreReleaseTime() {
		return preReleaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.pre_release_time
	 * @param preReleaseTime  the value for t_debt_transfer.pre_release_time
	 * @mbg.generated
	 */
	public void setPreReleaseTime(Date preReleaseTime) {
		this.preReleaseTime = preReleaseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.schedule
	 * @return  the value of t_debt_transfer.schedule
	 * @mbg.generated
	 */
	public BigDecimal getSchedule() {
		return schedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.schedule
	 * @param schedule  the value for t_debt_transfer.schedule
	 * @mbg.generated
	 */
	public void setSchedule(BigDecimal schedule) {
		this.schedule = schedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_debt_transfer.project_invest_id
	 * @return  the value of t_debt_transfer.project_invest_id
	 * @mbg.generated
	 */
	public Long getProjectInvestId() {
		return projectInvestId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_debt_transfer.project_invest_id
	 * @param projectInvestId  the value for t_debt_transfer.project_invest_id
	 * @mbg.generated
	 */
	public void setProjectInvestId(Long projectInvestId) {
		this.projectInvestId = projectInvestId;
	}
}