package com.juqijinfu.p2p.platform.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_experience_bid_account
 */
public class Experiencebidaccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   关联用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   体验金金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   体验金收益
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   冻结金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.freeze
     *
     * @mbg.generated
     */
    private BigDecimal freeze;

    /**
     * Database Column Remarks:
     *   上次领取时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.last_receive_time
     *
     * @mbg.generated
     */
    private Date lastReceiveTime;

    /**
     * Database Column Remarks:
     *   可领取体验金次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   体验金每次发放多少
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_account.every_grant
     *
     * @mbg.generated
     */
    private BigDecimal everyGrant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.id
     *
     * @return the value of t_experience_bid_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.id
     *
     * @param id the value for t_experience_bid_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.time
     *
     * @return the value of t_experience_bid_account.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.time
     *
     * @param time the value for t_experience_bid_account.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.user_id
     *
     * @return the value of t_experience_bid_account.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.user_id
     *
     * @param userId the value for t_experience_bid_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.amount
     *
     * @return the value of t_experience_bid_account.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.amount
     *
     * @param amount the value for t_experience_bid_account.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.balance
     *
     * @return the value of t_experience_bid_account.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.balance
     *
     * @param balance the value for t_experience_bid_account.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.freeze
     *
     * @return the value of t_experience_bid_account.freeze
     *
     * @mbg.generated
     */
    public BigDecimal getFreeze() {
        return freeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.freeze
     *
     * @param freeze the value for t_experience_bid_account.freeze
     *
     * @mbg.generated
     */
    public void setFreeze(BigDecimal freeze) {
        this.freeze = freeze;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.last_receive_time
     *
     * @return the value of t_experience_bid_account.last_receive_time
     *
     * @mbg.generated
     */
    public Date getLastReceiveTime() {
        return lastReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.last_receive_time
     *
     * @param lastReceiveTime the value for t_experience_bid_account.last_receive_time
     *
     * @mbg.generated
     */
    public void setLastReceiveTime(Date lastReceiveTime) {
        this.lastReceiveTime = lastReceiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.count
     *
     * @return the value of t_experience_bid_account.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.count
     *
     * @param count the value for t_experience_bid_account.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_account.every_grant
     *
     * @return the value of t_experience_bid_account.every_grant
     *
     * @mbg.generated
     */
    public BigDecimal getEveryGrant() {
        return everyGrant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_account.every_grant
     *
     * @param everyGrant the value for t_experience_bid_account.every_grant
     *
     * @mbg.generated
     */
    public void setEveryGrant(BigDecimal everyGrant) {
        this.everyGrant = everyGrant;
    }
}