package com.juqijinfu.p2p.platform.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_image_platform
 */
public class Imageplatform {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 上传时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 图片资源库类型 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.type
	 * @mbg.generated
	 */
	private Byte type;
	/**
	 * Database Column Remarks: 图片名称 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 图片路径 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.image_url
	 * @mbg.generated
	 */
	private String imageUrl;
	/**
	 * Database Column Remarks: 图片分辨率 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.image_resolution
	 * @mbg.generated
	 */
	private String imageResolution;
	/**
	 * Database Column Remarks: 图片大小 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.image_size
	 * @mbg.generated
	 */
	private String imageSize;
	/**
	 * Database Column Remarks: 图片格式 This field was generated by MyBatis Generator. This field corresponds to the database column t_image_platform.image_format
	 * @mbg.generated
	 */
	private String imageFormat;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.id
	 * @return  the value of t_image_platform.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.id
	 * @param id  the value for t_image_platform.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.time
	 * @return  the value of t_image_platform.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.time
	 * @param time  the value for t_image_platform.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.type
	 * @return  the value of t_image_platform.type
	 * @mbg.generated
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.type
	 * @param type  the value for t_image_platform.type
	 * @mbg.generated
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.name
	 * @return  the value of t_image_platform.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.name
	 * @param name  the value for t_image_platform.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.image_url
	 * @return  the value of t_image_platform.image_url
	 * @mbg.generated
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.image_url
	 * @param imageUrl  the value for t_image_platform.image_url
	 * @mbg.generated
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl == null ? null : imageUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.image_resolution
	 * @return  the value of t_image_platform.image_resolution
	 * @mbg.generated
	 */
	public String getImageResolution() {
		return imageResolution;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.image_resolution
	 * @param imageResolution  the value for t_image_platform.image_resolution
	 * @mbg.generated
	 */
	public void setImageResolution(String imageResolution) {
		this.imageResolution = imageResolution == null ? null : imageResolution.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.image_size
	 * @return  the value of t_image_platform.image_size
	 * @mbg.generated
	 */
	public String getImageSize() {
		return imageSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.image_size
	 * @param imageSize  the value for t_image_platform.image_size
	 * @mbg.generated
	 */
	public void setImageSize(String imageSize) {
		this.imageSize = imageSize == null ? null : imageSize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_image_platform.image_format
	 * @return  the value of t_image_platform.image_format
	 * @mbg.generated
	 */
	public String getImageFormat() {
		return imageFormat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_image_platform.image_format
	 * @param imageFormat  the value for t_image_platform.image_format
	 * @mbg.generated
	 */
	public void setImageFormat(String imageFormat) {
		this.imageFormat = imageFormat == null ? null : imageFormat.trim();
	}
}