package com.juqijinfu.p2p.platform.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_mass_email
 */
public class Massemail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   管理员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.supervisor_id
     *
     * @mbg.generated
     */
    private Long supervisorId;

    /**
     * Database Column Remarks:
     *   会员类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.member_type
     *
     * @mbg.generated
     */
    private Byte memberType;

    /**
     * Database Column Remarks:
     *   发送条数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     * Database Column Remarks:
     *   邮件主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   邮件内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_mass_email.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.id
     *
     * @return the value of t_mass_email.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.id
     *
     * @param id the value for t_mass_email.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.time
     *
     * @return the value of t_mass_email.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.time
     *
     * @param time the value for t_mass_email.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.supervisor_id
     *
     * @return the value of t_mass_email.supervisor_id
     *
     * @mbg.generated
     */
    public Long getSupervisorId() {
        return supervisorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.supervisor_id
     *
     * @param supervisorId the value for t_mass_email.supervisor_id
     *
     * @mbg.generated
     */
    public void setSupervisorId(Long supervisorId) {
        this.supervisorId = supervisorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.member_type
     *
     * @return the value of t_mass_email.member_type
     *
     * @mbg.generated
     */
    public Byte getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.member_type
     *
     * @param memberType the value for t_mass_email.member_type
     *
     * @mbg.generated
     */
    public void setMemberType(Byte memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.num
     *
     * @return the value of t_mass_email.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.num
     *
     * @param num the value for t_mass_email.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.title
     *
     * @return the value of t_mass_email.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.title
     *
     * @param title the value for t_mass_email.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_mass_email.content
     *
     * @return the value of t_mass_email.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_mass_email.content
     *
     * @param content the value for t_mass_email.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}