package com.juqijinfu.p2p.platform.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_project_invest
 */
public class Projectinvest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 投资人ID This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: U计划ID This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.project_id
	 * @mbg.generated
	 */
	private Long projectId;
	/**
	 * Database Column Remarks: 加入时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 计息开始时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.start_time
	 * @mbg.generated
	 */
	private Date startTime;
	/**
	 * Database Column Remarks: 加入金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.invest_amount
	 * @mbg.generated
	 */
	private BigDecimal investAmount;
	/**
	 * Database Column Remarks: 预计年利率 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.apr
	 * @mbg.generated
	 */
	private BigDecimal apr;
	/**
	 * Database Column Remarks: 是否续投 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.is_next_project
	 * @mbg.generated
	 */
	private Boolean isNextProject;
	/**
	 * Database Column Remarks: U计划加入记录状态 0：未投资 1：投资中 2：退出中 3：已退出 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.status
	 * @mbg.generated
	 */
	private Byte status;
	/**
	 * Database Column Remarks: 本金发放服务号 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.project_service_no
	 * @mbg.generated
	 */
	private String projectServiceNo;
	/**
	 * Database Column Remarks: 业务订单号，投标操作唯一标识 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.service_order_no
	 * @mbg.generated
	 */
	private String serviceOrderNo;
	/**
	 * Database Column Remarks: 交易订单号。托管方产生 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.trust_order_no
	 * @mbg.generated
	 */
	private String trustOrderNo;
	/**
	 * Database Column Remarks: 分摊到每一笔投资的借款服务费 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.loan_service_fee_divide
	 * @mbg.generated
	 */
	private BigDecimal loanServiceFeeDivide;
	/**
	 * Database Column Remarks: 结束时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.expire_time
	 * @mbg.generated
	 */
	private Date expireTime;
	/**
	 * Database Column Remarks: 提前退出时应得金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.expire_amount
	 * @mbg.generated
	 */
	private BigDecimal expireAmount;
	/**
	 * Database Column Remarks: 复投产生的小数位金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.repeat_fee
	 * @mbg.generated
	 */
	private BigDecimal repeatFee;
	/**
	 * Database Column Remarks: 登记投资入口: 1-pc  2-android  3-ios  4-wechat  This field was generated by MyBatis Generator. This field corresponds to the database column t_project_invest.client
	 * @mbg.generated
	 */
	private Byte client;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.id
	 * @return  the value of t_project_invest.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.id
	 * @param id  the value for t_project_invest.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.user_id
	 * @return  the value of t_project_invest.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.user_id
	 * @param userId  the value for t_project_invest.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.project_id
	 * @return  the value of t_project_invest.project_id
	 * @mbg.generated
	 */
	public Long getProjectId() {
		return projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.project_id
	 * @param projectId  the value for t_project_invest.project_id
	 * @mbg.generated
	 */
	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.time
	 * @return  the value of t_project_invest.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.time
	 * @param time  the value for t_project_invest.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.start_time
	 * @return  the value of t_project_invest.start_time
	 * @mbg.generated
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.start_time
	 * @param startTime  the value for t_project_invest.start_time
	 * @mbg.generated
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.invest_amount
	 * @return  the value of t_project_invest.invest_amount
	 * @mbg.generated
	 */
	public BigDecimal getInvestAmount() {
		return investAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.invest_amount
	 * @param investAmount  the value for t_project_invest.invest_amount
	 * @mbg.generated
	 */
	public void setInvestAmount(BigDecimal investAmount) {
		this.investAmount = investAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.apr
	 * @return  the value of t_project_invest.apr
	 * @mbg.generated
	 */
	public BigDecimal getApr() {
		return apr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.apr
	 * @param apr  the value for t_project_invest.apr
	 * @mbg.generated
	 */
	public void setApr(BigDecimal apr) {
		this.apr = apr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.is_next_project
	 * @return  the value of t_project_invest.is_next_project
	 * @mbg.generated
	 */
	public Boolean getIsNextProject() {
		return isNextProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.is_next_project
	 * @param isNextProject  the value for t_project_invest.is_next_project
	 * @mbg.generated
	 */
	public void setIsNextProject(Boolean isNextProject) {
		this.isNextProject = isNextProject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.status
	 * @return  the value of t_project_invest.status
	 * @mbg.generated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.status
	 * @param status  the value for t_project_invest.status
	 * @mbg.generated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.project_service_no
	 * @return  the value of t_project_invest.project_service_no
	 * @mbg.generated
	 */
	public String getProjectServiceNo() {
		return projectServiceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.project_service_no
	 * @param projectServiceNo  the value for t_project_invest.project_service_no
	 * @mbg.generated
	 */
	public void setProjectServiceNo(String projectServiceNo) {
		this.projectServiceNo = projectServiceNo == null ? null : projectServiceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.service_order_no
	 * @return  the value of t_project_invest.service_order_no
	 * @mbg.generated
	 */
	public String getServiceOrderNo() {
		return serviceOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.service_order_no
	 * @param serviceOrderNo  the value for t_project_invest.service_order_no
	 * @mbg.generated
	 */
	public void setServiceOrderNo(String serviceOrderNo) {
		this.serviceOrderNo = serviceOrderNo == null ? null : serviceOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.trust_order_no
	 * @return  the value of t_project_invest.trust_order_no
	 * @mbg.generated
	 */
	public String getTrustOrderNo() {
		return trustOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.trust_order_no
	 * @param trustOrderNo  the value for t_project_invest.trust_order_no
	 * @mbg.generated
	 */
	public void setTrustOrderNo(String trustOrderNo) {
		this.trustOrderNo = trustOrderNo == null ? null : trustOrderNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.loan_service_fee_divide
	 * @return  the value of t_project_invest.loan_service_fee_divide
	 * @mbg.generated
	 */
	public BigDecimal getLoanServiceFeeDivide() {
		return loanServiceFeeDivide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.loan_service_fee_divide
	 * @param loanServiceFeeDivide  the value for t_project_invest.loan_service_fee_divide
	 * @mbg.generated
	 */
	public void setLoanServiceFeeDivide(BigDecimal loanServiceFeeDivide) {
		this.loanServiceFeeDivide = loanServiceFeeDivide;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.expire_time
	 * @return  the value of t_project_invest.expire_time
	 * @mbg.generated
	 */
	public Date getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.expire_time
	 * @param expireTime  the value for t_project_invest.expire_time
	 * @mbg.generated
	 */
	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.expire_amount
	 * @return  the value of t_project_invest.expire_amount
	 * @mbg.generated
	 */
	public BigDecimal getExpireAmount() {
		return expireAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.expire_amount
	 * @param expireAmount  the value for t_project_invest.expire_amount
	 * @mbg.generated
	 */
	public void setExpireAmount(BigDecimal expireAmount) {
		this.expireAmount = expireAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.repeat_fee
	 * @return  the value of t_project_invest.repeat_fee
	 * @mbg.generated
	 */
	public BigDecimal getRepeatFee() {
		return repeatFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.repeat_fee
	 * @param repeatFee  the value for t_project_invest.repeat_fee
	 * @mbg.generated
	 */
	public void setRepeatFee(BigDecimal repeatFee) {
		this.repeatFee = repeatFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_project_invest.client
	 * @return  the value of t_project_invest.client
	 * @mbg.generated
	 */
	public Byte getClient() {
		return client;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_project_invest.client
	 * @param client  the value for t_project_invest.client
	 * @mbg.generated
	 */
	public void setClient(Byte client) {
		this.client = client;
	}
}