package com.juqijinfu.p2p.platform.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_red_packet_account
 */
public class Redpacketaccount {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_account.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_account.time
	 * @mbg.generated
	 */
	private Date time;
	/**
	 * Database Column Remarks: 用户ID This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_account.user_id
	 * @mbg.generated
	 */
	private Long userId;
	/**
	 * Database Column Remarks: 红包金额 This field was generated by MyBatis Generator. This field corresponds to the database column t_red_packet_account.balance
	 * @mbg.generated
	 */
	private BigDecimal balance;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_account.id
	 * @return  the value of t_red_packet_account.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_account.id
	 * @param id  the value for t_red_packet_account.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_account.time
	 * @return  the value of t_red_packet_account.time
	 * @mbg.generated
	 */
	public Date getTime() {
		return time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_account.time
	 * @param time  the value for t_red_packet_account.time
	 * @mbg.generated
	 */
	public void setTime(Date time) {
		this.time = time;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_account.user_id
	 * @return  the value of t_red_packet_account.user_id
	 * @mbg.generated
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_account.user_id
	 * @param userId  the value for t_red_packet_account.user_id
	 * @mbg.generated
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_red_packet_account.balance
	 * @return  the value of t_red_packet_account.balance
	 * @mbg.generated
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_red_packet_account.balance
	 * @param balance  the value for t_red_packet_account.balance
	 * @mbg.generated
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}
}