package com.juqijinfu.p2p.platform.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_wealthcircle_user
 */
public class Wealthcircleuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   邀请码编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.wc_code
     *
     * @mbg.generated
     */
    private String wcCode;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   推广人id(邀请码持有人)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.spreader_id
     *
     * @mbg.generated
     */
    private Long spreaderId;

    /**
     * Database Column Remarks:
     *   邀请码激活时间(被使用时间)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.active_time
     *
     * @mbg.generated
     */
    private Date activeTime;

    /**
     * Database Column Remarks:
     *   0:未使用，1:已使用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   被邀请人累计理财
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.total_invest
     *
     * @mbg.generated
     */
    private BigDecimal totalInvest;

    /**
     * Database Column Remarks:
     *   给邀请人带来累计返佣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.total_rebate
     *
     * @mbg.generated
     */
    private BigDecimal totalRebate;

    /**
     * Database Column Remarks:
     *   可领取返佣
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wealthcircle_user.recivable_rebate
     *
     * @mbg.generated
     */
    private BigDecimal recivableRebate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.id
     *
     * @return the value of t_wealthcircle_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.id
     *
     * @param id the value for t_wealthcircle_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.time
     *
     * @return the value of t_wealthcircle_user.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.time
     *
     * @param time the value for t_wealthcircle_user.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.wc_code
     *
     * @return the value of t_wealthcircle_user.wc_code
     *
     * @mbg.generated
     */
    public String getWcCode() {
        return wcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.wc_code
     *
     * @param wcCode the value for t_wealthcircle_user.wc_code
     *
     * @mbg.generated
     */
    public void setWcCode(String wcCode) {
        this.wcCode = wcCode == null ? null : wcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.user_id
     *
     * @return the value of t_wealthcircle_user.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.user_id
     *
     * @param userId the value for t_wealthcircle_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.spreader_id
     *
     * @return the value of t_wealthcircle_user.spreader_id
     *
     * @mbg.generated
     */
    public Long getSpreaderId() {
        return spreaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.spreader_id
     *
     * @param spreaderId the value for t_wealthcircle_user.spreader_id
     *
     * @mbg.generated
     */
    public void setSpreaderId(Long spreaderId) {
        this.spreaderId = spreaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.active_time
     *
     * @return the value of t_wealthcircle_user.active_time
     *
     * @mbg.generated
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.active_time
     *
     * @param activeTime the value for t_wealthcircle_user.active_time
     *
     * @mbg.generated
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.status
     *
     * @return the value of t_wealthcircle_user.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.status
     *
     * @param status the value for t_wealthcircle_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.total_invest
     *
     * @return the value of t_wealthcircle_user.total_invest
     *
     * @mbg.generated
     */
    public BigDecimal getTotalInvest() {
        return totalInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.total_invest
     *
     * @param totalInvest the value for t_wealthcircle_user.total_invest
     *
     * @mbg.generated
     */
    public void setTotalInvest(BigDecimal totalInvest) {
        this.totalInvest = totalInvest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.total_rebate
     *
     * @return the value of t_wealthcircle_user.total_rebate
     *
     * @mbg.generated
     */
    public BigDecimal getTotalRebate() {
        return totalRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.total_rebate
     *
     * @param totalRebate the value for t_wealthcircle_user.total_rebate
     *
     * @mbg.generated
     */
    public void setTotalRebate(BigDecimal totalRebate) {
        this.totalRebate = totalRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wealthcircle_user.recivable_rebate
     *
     * @return the value of t_wealthcircle_user.recivable_rebate
     *
     * @mbg.generated
     */
    public BigDecimal getRecivableRebate() {
        return recivableRebate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wealthcircle_user.recivable_rebate
     *
     * @param recivableRebate the value for t_wealthcircle_user.recivable_rebate
     *
     * @mbg.generated
     */
    public void setRecivableRebate(BigDecimal recivableRebate) {
        this.recivableRebate = recivableRebate;
    }
}