package cn.liuxingwei.spring.boot.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_audit_item_library
 */
public class Audititemlibrary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_item_library.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   入库时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_item_library.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_item_library.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   图片名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_item_library.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   图片名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_audit_item_library.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audit_item_library.id
     *
     * @return the value of t_audit_item_library.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audit_item_library.id
     *
     * @param id the value for t_audit_item_library.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audit_item_library.time
     *
     * @return the value of t_audit_item_library.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audit_item_library.time
     *
     * @param time the value for t_audit_item_library.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audit_item_library.user_id
     *
     * @return the value of t_audit_item_library.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audit_item_library.user_id
     *
     * @param userId the value for t_audit_item_library.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audit_item_library.name
     *
     * @return the value of t_audit_item_library.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audit_item_library.name
     *
     * @param name the value for t_audit_item_library.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_audit_item_library.url
     *
     * @return the value of t_audit_item_library.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_audit_item_library.url
     *
     * @param url the value for t_audit_item_library.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}