package cn.liuxingwei.spring.boot.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_bank_list
 */
public class Banklist {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_list.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   银行代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_list.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * Database Column Remarks:
     *   银行名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bank_list.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_list.id
     *
     * @return the value of t_bank_list.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_list.id
     *
     * @param id the value for t_bank_list.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_list.code
     *
     * @return the value of t_bank_list.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_list.code
     *
     * @param code the value for t_bank_list.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bank_list.name
     *
     * @return the value of t_bank_list.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bank_list.name
     *
     * @param name the value for t_bank_list.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}