package cn.liuxingwei.spring.boot.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_cps_account
 */
public class Cpsaccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cps_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cps_account.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cps_account.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   用户cps账户余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cps_account.balance
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     * Database Column Remarks:
     *   额外奖励余额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cps_account.additional_balance
     *
     * @mbg.generated
     */
    private BigDecimal additionalBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cps_account.id
     *
     * @return the value of t_cps_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cps_account.id
     *
     * @param id the value for t_cps_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cps_account.time
     *
     * @return the value of t_cps_account.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cps_account.time
     *
     * @param time the value for t_cps_account.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cps_account.user_id
     *
     * @return the value of t_cps_account.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cps_account.user_id
     *
     * @param userId the value for t_cps_account.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cps_account.balance
     *
     * @return the value of t_cps_account.balance
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cps_account.balance
     *
     * @param balance the value for t_cps_account.balance
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cps_account.additional_balance
     *
     * @return the value of t_cps_account.additional_balance
     *
     * @mbg.generated
     */
    public BigDecimal getAdditionalBalance() {
        return additionalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cps_account.additional_balance
     *
     * @param additionalBalance the value for t_cps_account.additional_balance
     *
     * @mbg.generated
     */
    public void setAdditionalBalance(BigDecimal additionalBalance) {
        this.additionalBalance = additionalBalance;
    }
}