package cn.liuxingwei.spring.boot.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_credit_level
 */
public class Creditlevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   信用等级名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   等级图标路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     * Database Column Remarks:
     *   图片分辨率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.image_resolution
     *
     * @mbg.generated
     */
    private String imageResolution;

    /**
     * Database Column Remarks:
     *   图片大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.image_size
     *
     * @mbg.generated
     */
    private String imageSize;

    /**
     * Database Column Remarks:
     *   文件格式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.image_format
     *
     * @mbg.generated
     */
    private String imageFormat;

    /**
     * Database Column Remarks:
     *   最低信用积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.min_credit_score
     *
     * @mbg.generated
     */
    private Integer minCreditScore;

    /**
     * Database Column Remarks:
     *   最高信用积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.max_credit_score
     *
     * @mbg.generated
     */
    private Integer maxCreditScore;

    /**
     * Database Column Remarks:
     *   信用等级高低排序号。数字越大等级越高
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_credit_level.order_no
     *
     * @mbg.generated
     */
    private Integer orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.id
     *
     * @return the value of t_credit_level.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.id
     *
     * @param id the value for t_credit_level.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.name
     *
     * @return the value of t_credit_level.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.name
     *
     * @param name the value for t_credit_level.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.image_url
     *
     * @return the value of t_credit_level.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.image_url
     *
     * @param imageUrl the value for t_credit_level.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.image_resolution
     *
     * @return the value of t_credit_level.image_resolution
     *
     * @mbg.generated
     */
    public String getImageResolution() {
        return imageResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.image_resolution
     *
     * @param imageResolution the value for t_credit_level.image_resolution
     *
     * @mbg.generated
     */
    public void setImageResolution(String imageResolution) {
        this.imageResolution = imageResolution == null ? null : imageResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.image_size
     *
     * @return the value of t_credit_level.image_size
     *
     * @mbg.generated
     */
    public String getImageSize() {
        return imageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.image_size
     *
     * @param imageSize the value for t_credit_level.image_size
     *
     * @mbg.generated
     */
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize == null ? null : imageSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.image_format
     *
     * @return the value of t_credit_level.image_format
     *
     * @mbg.generated
     */
    public String getImageFormat() {
        return imageFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.image_format
     *
     * @param imageFormat the value for t_credit_level.image_format
     *
     * @mbg.generated
     */
    public void setImageFormat(String imageFormat) {
        this.imageFormat = imageFormat == null ? null : imageFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.min_credit_score
     *
     * @return the value of t_credit_level.min_credit_score
     *
     * @mbg.generated
     */
    public Integer getMinCreditScore() {
        return minCreditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.min_credit_score
     *
     * @param minCreditScore the value for t_credit_level.min_credit_score
     *
     * @mbg.generated
     */
    public void setMinCreditScore(Integer minCreditScore) {
        this.minCreditScore = minCreditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.max_credit_score
     *
     * @return the value of t_credit_level.max_credit_score
     *
     * @mbg.generated
     */
    public Integer getMaxCreditScore() {
        return maxCreditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.max_credit_score
     *
     * @param maxCreditScore the value for t_credit_level.max_credit_score
     *
     * @mbg.generated
     */
    public void setMaxCreditScore(Integer maxCreditScore) {
        this.maxCreditScore = maxCreditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_credit_level.order_no
     *
     * @return the value of t_credit_level.order_no
     *
     * @mbg.generated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_credit_level.order_no
     *
     * @param orderNo the value for t_credit_level.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}