package cn.liuxingwei.spring.boot.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_experience_bid
 */
public class Experiencebid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   体验标名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   年利率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.apr
     *
     * @mbg.generated
     */
    private BigDecimal apr;

    /**
     * Database Column Remarks:
     *   借款期限(单位：天)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.period
     *
     * @mbg.generated
     */
    private Integer period;

    /**
     * Database Column Remarks:
     *   投标期限(单位：天)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.invest_period
     *
     * @mbg.generated
     */
    private Integer investPeriod;

    /**
     * Database Column Remarks:
     *   起投金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.min_invest_amount
     *
     * @mbg.generated
     */
    private BigDecimal minInvestAmount;

    /**
     * Database Column Remarks:
     *   还款方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.repayment_type
     *
     * @mbg.generated
     */
    private String repaymentType;

    /**
     * Database Column Remarks:
     *   状态:
     *   0-借款中
     *   1-还款中
     *   2-已结束
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   已投金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.has_invest_amount
     *
     * @mbg.generated
     */
    private BigDecimal hasInvestAmount;

    /**
     * Database Column Remarks:
     *   放款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.release_time
     *
     * @mbg.generated
     */
    private Date releaseTime;

    /**
     * Database Column Remarks:
     *   还款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.repayment_time
     *
     * @mbg.generated
     */
    private Date repaymentTime;

    /**
     * Database Column Remarks:
     *   实际还款时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.real_repayment_time
     *
     * @mbg.generated
     */
    private Date realRepaymentTime;

    /**
     * Database Column Remarks:
     *   加入人次
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid.invest_count
     *
     * @mbg.generated
     */
    private Integer investCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.id
     *
     * @return the value of t_experience_bid.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.id
     *
     * @param id the value for t_experience_bid.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.time
     *
     * @return the value of t_experience_bid.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.time
     *
     * @param time the value for t_experience_bid.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.title
     *
     * @return the value of t_experience_bid.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.title
     *
     * @param title the value for t_experience_bid.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.apr
     *
     * @return the value of t_experience_bid.apr
     *
     * @mbg.generated
     */
    public BigDecimal getApr() {
        return apr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.apr
     *
     * @param apr the value for t_experience_bid.apr
     *
     * @mbg.generated
     */
    public void setApr(BigDecimal apr) {
        this.apr = apr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.period
     *
     * @return the value of t_experience_bid.period
     *
     * @mbg.generated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.period
     *
     * @param period the value for t_experience_bid.period
     *
     * @mbg.generated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.invest_period
     *
     * @return the value of t_experience_bid.invest_period
     *
     * @mbg.generated
     */
    public Integer getInvestPeriod() {
        return investPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.invest_period
     *
     * @param investPeriod the value for t_experience_bid.invest_period
     *
     * @mbg.generated
     */
    public void setInvestPeriod(Integer investPeriod) {
        this.investPeriod = investPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.min_invest_amount
     *
     * @return the value of t_experience_bid.min_invest_amount
     *
     * @mbg.generated
     */
    public BigDecimal getMinInvestAmount() {
        return minInvestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.min_invest_amount
     *
     * @param minInvestAmount the value for t_experience_bid.min_invest_amount
     *
     * @mbg.generated
     */
    public void setMinInvestAmount(BigDecimal minInvestAmount) {
        this.minInvestAmount = minInvestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.repayment_type
     *
     * @return the value of t_experience_bid.repayment_type
     *
     * @mbg.generated
     */
    public String getRepaymentType() {
        return repaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.repayment_type
     *
     * @param repaymentType the value for t_experience_bid.repayment_type
     *
     * @mbg.generated
     */
    public void setRepaymentType(String repaymentType) {
        this.repaymentType = repaymentType == null ? null : repaymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.status
     *
     * @return the value of t_experience_bid.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.status
     *
     * @param status the value for t_experience_bid.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.has_invest_amount
     *
     * @return the value of t_experience_bid.has_invest_amount
     *
     * @mbg.generated
     */
    public BigDecimal getHasInvestAmount() {
        return hasInvestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.has_invest_amount
     *
     * @param hasInvestAmount the value for t_experience_bid.has_invest_amount
     *
     * @mbg.generated
     */
    public void setHasInvestAmount(BigDecimal hasInvestAmount) {
        this.hasInvestAmount = hasInvestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.release_time
     *
     * @return the value of t_experience_bid.release_time
     *
     * @mbg.generated
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.release_time
     *
     * @param releaseTime the value for t_experience_bid.release_time
     *
     * @mbg.generated
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.repayment_time
     *
     * @return the value of t_experience_bid.repayment_time
     *
     * @mbg.generated
     */
    public Date getRepaymentTime() {
        return repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.repayment_time
     *
     * @param repaymentTime the value for t_experience_bid.repayment_time
     *
     * @mbg.generated
     */
    public void setRepaymentTime(Date repaymentTime) {
        this.repaymentTime = repaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.real_repayment_time
     *
     * @return the value of t_experience_bid.real_repayment_time
     *
     * @mbg.generated
     */
    public Date getRealRepaymentTime() {
        return realRepaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.real_repayment_time
     *
     * @param realRepaymentTime the value for t_experience_bid.real_repayment_time
     *
     * @mbg.generated
     */
    public void setRealRepaymentTime(Date realRepaymentTime) {
        this.realRepaymentTime = realRepaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid.invest_count
     *
     * @return the value of t_experience_bid.invest_count
     *
     * @mbg.generated
     */
    public Integer getInvestCount() {
        return investCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid.invest_count
     *
     * @param investCount the value for t_experience_bid.invest_count
     *
     * @mbg.generated
     */
    public void setInvestCount(Integer investCount) {
        this.investCount = investCount;
    }
}