package cn.liuxingwei.spring.boot.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_experience_bid_invest
 */
public class Experiencebidinvest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   投标时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   体验标ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.bid_id
     *
     * @mbg.generated
     */
    private Long bidId;

    /**
     * Database Column Remarks:
     *   投标金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   预收益
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.income
     *
     * @mbg.generated
     */
    private BigDecimal income;

    /**
     * Database Column Remarks:
     *   体验标投资入口:
     *   1-pc 
     *   2-android 
     *   3-ios 
     *   4-wechat 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_experience_bid_invest.client
     *
     * @mbg.generated
     */
    private Byte client;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.id
     *
     * @return the value of t_experience_bid_invest.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.id
     *
     * @param id the value for t_experience_bid_invest.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.time
     *
     * @return the value of t_experience_bid_invest.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.time
     *
     * @param time the value for t_experience_bid_invest.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.user_id
     *
     * @return the value of t_experience_bid_invest.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.user_id
     *
     * @param userId the value for t_experience_bid_invest.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.bid_id
     *
     * @return the value of t_experience_bid_invest.bid_id
     *
     * @mbg.generated
     */
    public Long getBidId() {
        return bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.bid_id
     *
     * @param bidId the value for t_experience_bid_invest.bid_id
     *
     * @mbg.generated
     */
    public void setBidId(Long bidId) {
        this.bidId = bidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.amount
     *
     * @return the value of t_experience_bid_invest.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.amount
     *
     * @param amount the value for t_experience_bid_invest.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.income
     *
     * @return the value of t_experience_bid_invest.income
     *
     * @mbg.generated
     */
    public BigDecimal getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.income
     *
     * @param income the value for t_experience_bid_invest.income
     *
     * @mbg.generated
     */
    public void setIncome(BigDecimal income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_experience_bid_invest.client
     *
     * @return the value of t_experience_bid_invest.client
     *
     * @mbg.generated
     */
    public Byte getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_experience_bid_invest.client
     *
     * @param client the value for t_experience_bid_invest.client
     *
     * @mbg.generated
     */
    public void setClient(Byte client) {
        this.client = client;
    }
}