package cn.liuxingwei.spring.boot.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_payment_call_back
 */
public class Paymentcallback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_call_back.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_call_back.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   托管请求标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_call_back.request_mark
     *
     * @mbg.generated
     */
    private String requestMark;

    /**
     * Database Column Remarks:
     *   日志类型 0：回调日志 1：查询日志
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_call_back.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     * Database Column Remarks:
     *   回调参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_payment_call_back.cb_params
     *
     * @mbg.generated
     */
    private String cbParams;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_call_back.id
     *
     * @return the value of t_payment_call_back.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_call_back.id
     *
     * @param id the value for t_payment_call_back.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_call_back.time
     *
     * @return the value of t_payment_call_back.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_call_back.time
     *
     * @param time the value for t_payment_call_back.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_call_back.request_mark
     *
     * @return the value of t_payment_call_back.request_mark
     *
     * @mbg.generated
     */
    public String getRequestMark() {
        return requestMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_call_back.request_mark
     *
     * @param requestMark the value for t_payment_call_back.request_mark
     *
     * @mbg.generated
     */
    public void setRequestMark(String requestMark) {
        this.requestMark = requestMark == null ? null : requestMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_call_back.data_type
     *
     * @return the value of t_payment_call_back.data_type
     *
     * @mbg.generated
     */
    public Integer getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_call_back.data_type
     *
     * @param dataType the value for t_payment_call_back.data_type
     *
     * @mbg.generated
     */
    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_payment_call_back.cb_params
     *
     * @return the value of t_payment_call_back.cb_params
     *
     * @mbg.generated
     */
    public String getCbParams() {
        return cbParams;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_payment_call_back.cb_params
     *
     * @param cbParams the value for t_payment_call_back.cb_params
     *
     * @mbg.generated
     */
    public void setCbParams(String cbParams) {
        this.cbParams = cbParams == null ? null : cbParams.trim();
    }
}