package cn.liuxingwei.spring.boot.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_product
 */
public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   添加时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   产品类型
     *   1-普通
     *   2-信用
     *   3-净值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   产品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_url
     *
     * @mbg.generated
     */
    private String imageUrl;

    /**
     * Database Column Remarks:
     *   图片分辨率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_resolution
     *
     * @mbg.generated
     */
    private String imageResolution;

    /**
     * Database Column Remarks:
     *   文件大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_size
     *
     * @mbg.generated
     */
    private String imageSize;

    /**
     * Database Column Remarks:
     *   文件格式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_format
     *
     * @mbg.generated
     */
    private String imageFormat;

    /**
     * Database Column Remarks:
     *   app产品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_app_url
     *
     * @mbg.generated
     */
    private String imageAppUrl;

    /**
     * Database Column Remarks:
     *   app图片分辨率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_app_resolution
     *
     * @mbg.generated
     */
    private String imageAppResolution;

    /**
     * Database Column Remarks:
     *   app文件大小
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_app_size
     *
     * @mbg.generated
     */
    private String imageAppSize;

    /**
     * Database Column Remarks:
     *   app文件格式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.image_app_format
     *
     * @mbg.generated
     */
    private String imageAppFormat;

    /**
     * Database Column Remarks:
     *   排序时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.order_time
     *
     * @mbg.generated
     */
    private Date orderTime;

    /**
     * Database Column Remarks:
     *   借款额度下限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.min_amount
     *
     * @mbg.generated
     */
    private BigDecimal minAmount;

    /**
     * Database Column Remarks:
     *   借款额度上限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.max_amount
     *
     * @mbg.generated
     */
    private BigDecimal maxAmount;

    /**
     * Database Column Remarks:
     *   年利率下限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.min_apr
     *
     * @mbg.generated
     */
    private BigDecimal minApr;

    /**
     * Database Column Remarks:
     *   年利率上限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.max_apr
     *
     * @mbg.generated
     */
    private BigDecimal maxApr;

    /**
     * Database Column Remarks:
     *   借款期限单位。
     *   1-天
     *   2-月
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.period_unit
     *
     * @mbg.generated
     */
    private Byte periodUnit;

    /**
     * Database Column Remarks:
     *   借款期限下限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.min_period
     *
     * @mbg.generated
     */
    private Integer minPeriod;

    /**
     * Database Column Remarks:
     *   借款期限上限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.max_period
     *
     * @mbg.generated
     */
    private Integer maxPeriod;

    /**
     * Database Column Remarks:
     *   还款方式
     *   。1-先息后本
     *   ；2-等本等息；
     *   3-一次性还款；
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.repayment_type
     *
     * @mbg.generated
     */
    private String repaymentType;

    /**
     * Database Column Remarks:
     *   购买方式。
     *   1-按金额
     *   2-按份数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.buy_type
     *
     * @mbg.generated
     */
    private Byte buyType;

    /**
     * Database Column Remarks:
     *   按金额购买：起投金额。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.min_invest_amount
     *
     * @mbg.generated
     */
    private BigDecimal minInvestAmount;

    /**
     * Database Column Remarks:
     *   拆分份数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.invest_copies
     *
     * @mbg.generated
     */
    private Integer investCopies;

    /**
     * Database Column Remarks:
     *   保证金百分比
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.bail_scale
     *
     * @mbg.generated
     */
    private BigDecimal bailScale;

    /**
     * Database Column Remarks:
     *   借款服务费、理财服务费、逾期罚息规则（以JSON串的形式存储）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.service_fee_rule
     *
     * @mbg.generated
     */
    private String serviceFeeRule;

    /**
     * Database Column Remarks:
     *   审核科目ID列表。
     *   多个科目间以逗号隔开。
     *   如：1,2,3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.audit_subjects
     *
     * @mbg.generated
     */
    private String auditSubjects;

    /**
     * Database Column Remarks:
     *   启用标识。
     *   0-下架
     *   1-上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product.is_use
     *
     * @mbg.generated
     */
    private Boolean isUse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.id
     *
     * @return the value of t_product.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.id
     *
     * @param id the value for t_product.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.time
     *
     * @return the value of t_product.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.time
     *
     * @param time the value for t_product.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.type
     *
     * @return the value of t_product.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.type
     *
     * @param type the value for t_product.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.name
     *
     * @return the value of t_product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.name
     *
     * @param name the value for t_product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_url
     *
     * @return the value of t_product.image_url
     *
     * @mbg.generated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_url
     *
     * @param imageUrl the value for t_product.image_url
     *
     * @mbg.generated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_resolution
     *
     * @return the value of t_product.image_resolution
     *
     * @mbg.generated
     */
    public String getImageResolution() {
        return imageResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_resolution
     *
     * @param imageResolution the value for t_product.image_resolution
     *
     * @mbg.generated
     */
    public void setImageResolution(String imageResolution) {
        this.imageResolution = imageResolution == null ? null : imageResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_size
     *
     * @return the value of t_product.image_size
     *
     * @mbg.generated
     */
    public String getImageSize() {
        return imageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_size
     *
     * @param imageSize the value for t_product.image_size
     *
     * @mbg.generated
     */
    public void setImageSize(String imageSize) {
        this.imageSize = imageSize == null ? null : imageSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_format
     *
     * @return the value of t_product.image_format
     *
     * @mbg.generated
     */
    public String getImageFormat() {
        return imageFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_format
     *
     * @param imageFormat the value for t_product.image_format
     *
     * @mbg.generated
     */
    public void setImageFormat(String imageFormat) {
        this.imageFormat = imageFormat == null ? null : imageFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_app_url
     *
     * @return the value of t_product.image_app_url
     *
     * @mbg.generated
     */
    public String getImageAppUrl() {
        return imageAppUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_app_url
     *
     * @param imageAppUrl the value for t_product.image_app_url
     *
     * @mbg.generated
     */
    public void setImageAppUrl(String imageAppUrl) {
        this.imageAppUrl = imageAppUrl == null ? null : imageAppUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_app_resolution
     *
     * @return the value of t_product.image_app_resolution
     *
     * @mbg.generated
     */
    public String getImageAppResolution() {
        return imageAppResolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_app_resolution
     *
     * @param imageAppResolution the value for t_product.image_app_resolution
     *
     * @mbg.generated
     */
    public void setImageAppResolution(String imageAppResolution) {
        this.imageAppResolution = imageAppResolution == null ? null : imageAppResolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_app_size
     *
     * @return the value of t_product.image_app_size
     *
     * @mbg.generated
     */
    public String getImageAppSize() {
        return imageAppSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_app_size
     *
     * @param imageAppSize the value for t_product.image_app_size
     *
     * @mbg.generated
     */
    public void setImageAppSize(String imageAppSize) {
        this.imageAppSize = imageAppSize == null ? null : imageAppSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.image_app_format
     *
     * @return the value of t_product.image_app_format
     *
     * @mbg.generated
     */
    public String getImageAppFormat() {
        return imageAppFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.image_app_format
     *
     * @param imageAppFormat the value for t_product.image_app_format
     *
     * @mbg.generated
     */
    public void setImageAppFormat(String imageAppFormat) {
        this.imageAppFormat = imageAppFormat == null ? null : imageAppFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.order_time
     *
     * @return the value of t_product.order_time
     *
     * @mbg.generated
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.order_time
     *
     * @param orderTime the value for t_product.order_time
     *
     * @mbg.generated
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.min_amount
     *
     * @return the value of t_product.min_amount
     *
     * @mbg.generated
     */
    public BigDecimal getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.min_amount
     *
     * @param minAmount the value for t_product.min_amount
     *
     * @mbg.generated
     */
    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.max_amount
     *
     * @return the value of t_product.max_amount
     *
     * @mbg.generated
     */
    public BigDecimal getMaxAmount() {
        return maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.max_amount
     *
     * @param maxAmount the value for t_product.max_amount
     *
     * @mbg.generated
     */
    public void setMaxAmount(BigDecimal maxAmount) {
        this.maxAmount = maxAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.min_apr
     *
     * @return the value of t_product.min_apr
     *
     * @mbg.generated
     */
    public BigDecimal getMinApr() {
        return minApr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.min_apr
     *
     * @param minApr the value for t_product.min_apr
     *
     * @mbg.generated
     */
    public void setMinApr(BigDecimal minApr) {
        this.minApr = minApr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.max_apr
     *
     * @return the value of t_product.max_apr
     *
     * @mbg.generated
     */
    public BigDecimal getMaxApr() {
        return maxApr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.max_apr
     *
     * @param maxApr the value for t_product.max_apr
     *
     * @mbg.generated
     */
    public void setMaxApr(BigDecimal maxApr) {
        this.maxApr = maxApr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.period_unit
     *
     * @return the value of t_product.period_unit
     *
     * @mbg.generated
     */
    public Byte getPeriodUnit() {
        return periodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.period_unit
     *
     * @param periodUnit the value for t_product.period_unit
     *
     * @mbg.generated
     */
    public void setPeriodUnit(Byte periodUnit) {
        this.periodUnit = periodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.min_period
     *
     * @return the value of t_product.min_period
     *
     * @mbg.generated
     */
    public Integer getMinPeriod() {
        return minPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.min_period
     *
     * @param minPeriod the value for t_product.min_period
     *
     * @mbg.generated
     */
    public void setMinPeriod(Integer minPeriod) {
        this.minPeriod = minPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.max_period
     *
     * @return the value of t_product.max_period
     *
     * @mbg.generated
     */
    public Integer getMaxPeriod() {
        return maxPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.max_period
     *
     * @param maxPeriod the value for t_product.max_period
     *
     * @mbg.generated
     */
    public void setMaxPeriod(Integer maxPeriod) {
        this.maxPeriod = maxPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.repayment_type
     *
     * @return the value of t_product.repayment_type
     *
     * @mbg.generated
     */
    public String getRepaymentType() {
        return repaymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.repayment_type
     *
     * @param repaymentType the value for t_product.repayment_type
     *
     * @mbg.generated
     */
    public void setRepaymentType(String repaymentType) {
        this.repaymentType = repaymentType == null ? null : repaymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.buy_type
     *
     * @return the value of t_product.buy_type
     *
     * @mbg.generated
     */
    public Byte getBuyType() {
        return buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.buy_type
     *
     * @param buyType the value for t_product.buy_type
     *
     * @mbg.generated
     */
    public void setBuyType(Byte buyType) {
        this.buyType = buyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.min_invest_amount
     *
     * @return the value of t_product.min_invest_amount
     *
     * @mbg.generated
     */
    public BigDecimal getMinInvestAmount() {
        return minInvestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.min_invest_amount
     *
     * @param minInvestAmount the value for t_product.min_invest_amount
     *
     * @mbg.generated
     */
    public void setMinInvestAmount(BigDecimal minInvestAmount) {
        this.minInvestAmount = minInvestAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.invest_copies
     *
     * @return the value of t_product.invest_copies
     *
     * @mbg.generated
     */
    public Integer getInvestCopies() {
        return investCopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.invest_copies
     *
     * @param investCopies the value for t_product.invest_copies
     *
     * @mbg.generated
     */
    public void setInvestCopies(Integer investCopies) {
        this.investCopies = investCopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.bail_scale
     *
     * @return the value of t_product.bail_scale
     *
     * @mbg.generated
     */
    public BigDecimal getBailScale() {
        return bailScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.bail_scale
     *
     * @param bailScale the value for t_product.bail_scale
     *
     * @mbg.generated
     */
    public void setBailScale(BigDecimal bailScale) {
        this.bailScale = bailScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.service_fee_rule
     *
     * @return the value of t_product.service_fee_rule
     *
     * @mbg.generated
     */
    public String getServiceFeeRule() {
        return serviceFeeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.service_fee_rule
     *
     * @param serviceFeeRule the value for t_product.service_fee_rule
     *
     * @mbg.generated
     */
    public void setServiceFeeRule(String serviceFeeRule) {
        this.serviceFeeRule = serviceFeeRule == null ? null : serviceFeeRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.audit_subjects
     *
     * @return the value of t_product.audit_subjects
     *
     * @mbg.generated
     */
    public String getAuditSubjects() {
        return auditSubjects;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.audit_subjects
     *
     * @param auditSubjects the value for t_product.audit_subjects
     *
     * @mbg.generated
     */
    public void setAuditSubjects(String auditSubjects) {
        this.auditSubjects = auditSubjects == null ? null : auditSubjects.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product.is_use
     *
     * @return the value of t_product.is_use
     *
     * @mbg.generated
     */
    public Boolean getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product.is_use
     *
     * @param isUse the value for t_product.is_use
     *
     * @mbg.generated
     */
    public void setIsUse(Boolean isUse) {
        this.isUse = isUse;
    }
}